### PR TITLE
App Submission: Sqlitebrowser

### PR DESCRIPTION
**Pull request by IMPranshu**
# App Submission

### Have the OG dev's permission?
Yes. Absolutely. https://github.com/getumbrel/umbrel-apps/pull/267#issuecomment-1618345854

### Sqlitebrowser
...

### 256x256 SVG icon
https://svgshare.com/i/vVK.svg
...

### Gallery images
image
Screenshot from 2022-11-11 00-25-52
Screenshot from 2022-11-11 00-26-12
Screenshot from 2022-11-11 00-26-22

...

### I have tested my app on:
- [x] [Umbrel dev environment](https://github.com/getumbrel/umbrel-dev)
- [x] [Umbrel OS on a Raspberry Pi 4](https://github.com/getumbrel/umbrel-os)
- [x] [Custom Umbrel install on Linux](https://github.com/getumbrel/umbrel#-installation)

### CODE REVIEW

**Comment by nmfretz** [comment]
Closing for now (see here: https://github.com/getumbrel/umbrel-apps/issues/687#issuecomment-1666223355).

**Comment by bureaugewas** [comment]
I'm looking to use database infrastructure apps on Umbrel. Could you please open this PR again?

**Comment by IMPranshu** [comment]
Please open this PR. I have also taken permission from the developer team https://github.com/sqlitebrowser/sqlitebrowser/issues/3391

**Comment by al-lac** [comment]
Hey @IMPranshu, someone else already opened a PR here: #2223

**Pull request closed without merging**
