### PR TITLE
Update Jam to v0.1.1

### PR DESCRIPTION
**Pull request by theborakompanioni**
This version includes:
- Jam: [v0.1.1](https://github.com/joinmarket-webui/jam/releases/tag/v0.1.1)
- joinmarket-clientserver: [v0.9.8](https://github.com/JoinMarket-Org/joinmarket-clientserver/releases/tag/v0.9.8)

All notable changes of the UI can be seen in the [Jam v0.1.1 changelog](https://github.com/joinmarket-webui/jam/blob/v0.1.1/CHANGELOG.md)

Updates to the image:
- feat: randomize mandatory fee config values [#66](https://github.com/joinmarket-webui/jam-docker/pull/66)

### CODE REVIEW

**Review by nevets963 — COMMENTED** [review]
@theborakompanioni Thanks for Jam app update! I gave it a test on my `arm64` and `amd64` Umbrel servers and they seem to run OK.

Except for `amd64` where I run `regtest` and I now get this new error message:
```
Unhandled Thrown Error!
404 Not Found

💿 Hey developer 👋

You can provide a way better UX than this when your app throws errors by providing your own errorElement props on <Route>
```

If you think this is nothing serious then I'm happy to approve this.

**Comment by theborakompanioni** [comment]
> @theborakompanioni Thanks for Jam app update! I gave it a test on my `arm64` and `amd64` Umbrel servers and they seem to run OK.
> 
> Except for `amd64` where I run `regtest` and I now get this new error message:
> 
> ```
> Unhandled Thrown Error!
> 404 Not Found
> 
> 💿 Hey developer 👋
> 
> You can provide a way better UX than this when your app throws errors by providing your own errorElement props on <Route>
> ```
> 
> If you think this is nothing serious then I'm happy to approve this.

Thanks you so much for the heads-up. This should definitely not happen. Would you possibly be so kind as to try again after waiting a few seconds for the backend to come up and with browser cache cleared?

Got this too during development (https://github.com/joinmarket-webui/jam/pull/519#discussion_r985961844) but only for brief moments, subsequently redirecting to the index page. Looking at the code, it seems this might happen if the backend is down (or still booting - there is a small delay), so from this point of view I suggest it is safe to merge.
However, this is not a nice experience and will be addressed in the next release.

**Comment by nevets963** [comment]
I just tried again after having it up for >12 hours and cleared my browser cache but I still get the error. I'm not sure how to interpret this:
> it is safe to merge only if the backend comes up normally without any errors on amd64

Does that mean you want to patch this case up? Or because it's likely only an issue on `regtest`, then we're good to merge?

**Comment by theborakompanioni** [comment]
> Does that mean you want to patch this case up? Or because it's likely only an issue on `regtest`, then we're good to merge?

After chatting, the issue has been identified (the [infamous descriptor wallet bug](https://github.com/joinmarket-webui/jam/issues/502)). 
Next release will have a proper error message, but this PR is safe to merge!

Thank you for your help and your patience @nevets963 :orange_heart:

**Pull request merged**
