### PR TITLE
App Submission: MyLar3

### PR DESCRIPTION
**Pull request by IMPranshu**
# App Submission

### MyLar3
...

### 256x256 SVG icon
https://svgshare.com/i/neP.svg
...

### Gallery images
Screenshot from 2022-10-25 20-55-16
Screenshot from 2022-10-25 20-55-41
Screenshot from 2022-10-25 20-56-17
Screenshot from 2022-10-25 20-56-01

...

### I have tested my app on:
- [ ] [Umbrel dev environment](https://github.com/getumbrel/umbrel-dev)
- [x] [Umbrel OS on a Raspberry Pi 4](https://github.com/getumbrel/umbrel-os)
- [x] [Custom Umbrel install on Linux](https://github.com/getumbrel/umbrel#-installation)

### CODE REVIEW

**Comment by IMPranshu** [comment]
This App is now working on Umbrel. Had to remove `app-proxy`. I have verified it on both of my devices. Sorry!

**Comment by nevets963** [comment]
@IMPranshu What was the issue you had when using the App Proxy?

**Comment by IMPranshu** [comment]
When I was adding the `app proxy` the apps were stuck at `starting` in the Umbrel dashboard. This was happening with all of my apps. Don't know if it was a local issue but I removed the `app proxy` and the app worked fine.

**Comment by nevets963** [comment]
@IMPranshu I'm not sure what issue you could be having with the App Proxy. I just added it and it's working fine (https://github.com/getumbrel/umbrel-apps/pull/221/commits/029fdd911f77fe9bd42451bbba7b34d572fc7f8a). It's potentially because you were trying to open the same port twice, ie the app proxy and the `server` container were trying to open the same port on the host.

**Comment by IMPranshu** [comment]
I think the same was cached and was causing the error in all of my apps.

**Pull request closed without merging**
