### PR TITLE
2022 08 16 suredbits wallet update

### PR DESCRIPTION
**Pull request by Christewart**
We are about to cut a 1.9.3 for the Suredbits Wallet.

This modifies some configurations on our umbrel deployment as we are no longer specify the [USER id in our docker images](https://github.com/bitcoin-s/bitcoin-s/pull/4601)

I still need to test this with a fresh umbrel install.

### CODE REVIEW

**Comment by Christewart** [comment]
@nevets963 This should be ready for review, for testing we could pick this up if you have time :-) 

https://github.com/getumbrel/umbrel-apps/pull/61#issuecomment-1178119431

**Comment by Christewart** [comment]
@nevets963 Where do you get image hashes from? It seems your hashes are different than what is on docker hub 

https://hub.docker.com/layers/bitcoinscala/bitcoin-s-server/1.9.3/images/sha256-f874c4547631aacb84921b34c521d63eca2bc5924e4e2b45b30250c84a9f84a1?context=repo

Screenshot from 2022-09-12 07-39-58

**Comment by nevets963** [comment]
@Christewart These image hashes are for specific OS/Arch (as shown in the screenshot by the dropdown menu). You can get a multi-arch digest by running: `docker pull <image>:<tag>` and then the digest will be at the bottom.

For example:
```
docker pull bitcoinscala/wallet-server-ui:1.9.3
1.9.3: Pulling from bitcoinscala/wallet-server-ui
824b15f81d65: Already exists
325d38bcb229: Already exists
d6d638bf61bf: Already exists
55daac95cedf: Already exists
4c701498752d: Already exists
09f410b4659e: Pull complete
320991b72725: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:dfbded611403fb03dac45fe915320079933e8f864e0942b7fb3ddea017e2b8dd
Status: Downloaded newer image for bitcoinscala/wallet-server-ui:1.9.3
docker.io/bitcoinscala/wallet-server-ui:1.9.3
```

`sha256:dfbded611403fb03dac45fe915320079933e8f864e0942b7fb3ddea017e2b8dd` in this case for `bitcoinscala/wallet-server-ui:1.9.3`

**Comment by nevets963** [comment]
> @nevets963 This should be ready for review, for testing we could pick this up if you have time :-)
> 
> [#61 (comment)](https://github.com/getumbrel/umbrel-apps/pull/61#issuecomment-1178119431)

Yes absolutely, let's try it! Can you message me on TG? I'll send over Tor address and we can use an interesting oracle 😄 

This is tested on `amd64` and `arm64`. Ready to merge in 🚀

**Pull request merged**
