### PR TITLE
Update Torq to v1.1.5

### PR DESCRIPTION
**Pull request by ohenrik**
* Package upgrades
* Bugfixes:
    * Fixed Incorrect ordering of locked columns in table views
    * CLN payment status was stuck or not showing correct status

### CODE REVIEW

**Review by ParthJadhav — APPROVED** [review]
- Tested Image Architecture
- Updated old version to new version

**Comment by nmfretz** [comment]
Thanks @ohenrik! And thanks for reviewing @ParthJadhav.

Tested on arm64 and x86(amd64). Going live.

FYI, I noticed a whitespace issue in the release notes, but have merged anyways because:
1) I don't have write-access to your repo to quickly fix this, and I didn't want to hold your update up any further.
1) this is a very minor thing that does not affect app performance.
2) I see Torq 1.2.0 has been released so this version here will be short-lived in the app store. 

image

**Comment by nmfretz** [comment]
Actually I ended up fixing here: [1de5e2a](https://github.com/getumbrel/umbrel-apps/commit/1de5e2aeab6e905ad7a9f8e17ff94af3c61d80ee)

**Comment by ohenrik** [comment]
@nmfretz Apologies for not responding earlier and thank you for fixing this. I have created the new 1.2.1 update PR now (https://github.com/getumbrel/umbrel-apps/pull/801). Do you want me to give you access to our fork of the repo? (For small fixes like this).

**Comment by nmfretz** [comment]
No problem at all @ohenrik! Totally up to you on whether you want to give me access. I'm not sure if this is possible, but potentially you could give access to the `getumbrel` organization so that anyone in that org has access. That way if I'm no longer part of the Umbrel org in the future I would no longer have access to your fork.

**Pull request merged**
