### PR TITLE
upgrade to boltz-client in rtl

### PR DESCRIPTION
**Pull request by jackstar12**
This pr replaces `boltz-lnd` with its successor [boltz-client](https://github.com/BoltzExchange/boltz-client).
Its completely backwards compatible and the migration is well tested.

### CODE REVIEW

**Comment by kilrau** [comment]
Could you give this a look? @nmfretz 

We tested the migration from boltz-lnd to boltz-client in a smaller beta [with a couple of external umbrel users](https://twitter.com/Boltzhq/status/1758533595310793102). All worked as expected. Also note, that merging this doesn't change anything feature-wise for the user but is a major requirement for us to not block our work @ RTL to enable new Boltz Client like e.g. [CLN support](https://github.com/Ride-The-Lightning/RTL/pull/1366) and more.

**Comment by kilrau** [comment]
Friendly bump @nmfretz

**Comment by nmfretz** [comment]
Hi @jackstar12 and @kilrau, sorry for the delay.

It looks like the `2.0.x-compat` docker images are not multi-architecture (right now they are only amd64), so right now an update will break the app for Raspberry Pi users.

Can you please push a multi-arch image? In the meantime I'll test this on armd64.

**Comment by nmfretz** [comment]
Also, one other consideration:

In order for current RTL users to be notified of an app update we need to update the `version` in the umbrel-app.yml. The current version in the yml file is `0.14.1-beta`. What would you like to change this to? It can be something as simple as just doing `0.14.1-beta-boltzclient` or something.

**Comment by jackstar12** [comment]
@nmfretz I've pushed and updated to the multi-version platform of the image. Your proposed `0.14.1-beta-boltzclient` sounds like a good, we can go with that.

**Comment by kilrau** [comment]
With regards to release notes: while most users won't notice the change, boltz-client uses [taproot swaps ](https://blog.boltz.exchange/p/introducing-taproot-swaps-putting)by default now (boltz-lnd didn't support taproot swaps). Might be worth to mention.

**Comment by nmfretz** [comment]
Perfect, thanks @jackstar12 and @kilrau. I have tested on both arm64 and x86. Going live now.

It looks like I do not have permission to push changes to `BoltzExchange/rtl-boltz-client` so I will bump the version and add release notes to the manifest in a separate commit

**Pull request merged**
