### PR TITLE
Update Syncthing to v1.23.0

### PR DESCRIPTION
**Pull request by jon-ryan**

### CODE REVIEW

**Comment by jon-ryan** [comment]
I'm not sure about the image digest, as it's different for each architecture..

**Review by nevets963 — COMMENTED** [review]
@jon-ryan Many thanks for the PR to update Syncthing in the app store!

Would you mind adding the release note for v1.23.0 into the app manifest (`umbrel-app.yml`)? Here is example from the Bitcoin app: https://github.com/getumbrel/umbrel-apps/blob/dae77d2ee2af059f4c996b66c7474d9af3b437f0/bitcoin/umbrel-app.yml#L36-L55

**Comment by jon-ryan** [comment]
@nevets963 I added the release notes of release 1.23.0. I'm a little unsure about the image digest. I took the one printed out after `docker pull syncthing/syncthing`

**Review by nevets963 — APPROVED** [review]
@jon-ryan Thanks again for the PR and for the requested changes. I just made a few changes including restoring the `submitter` metadata (which we're currently using for the person/entity that submits the app into the app store). Your contribution will of course appear within the contributors section of this repo!

Tested on `arm64` and `amd64`.

Merging now 🚀

**Pull request merged**
