### PR TITLE
Update WoofBot to v0.5.2

### PR DESCRIPTION
**Pull request by woofbotapp**
Tested on my raspberry pi.

This is a minor issue for those who update instead of uninstalling and reinstalling:
https://github.com/getumbrel/umbrel-apps/issues/346

(Minor issue, those logs are only needed for debugging purposes).

### CODE REVIEW

**Review by nevets963 — COMMENTED** [review]
@woofbotapp Thanks for the app update!

Currently we have a whitelist of files/folders that we can copy during an app update and as you say, because `root` will perform the operation, it will create the folder on the host under `root` too. To solve this issue, we can create a `pre-start` hook (here is a rough example: https://github.com/getumbrel/umbrel-apps/blob/9e2756aee9088d2639a95c94eafc9cb9c896594a/bitcoin/hooks/pre-start) that checks for the existence of the `server-logs` folder, and if not, create it and `chown` to `1000:1000`.

I can help here, but I would need write access.

**Comment by woofbotapp** [comment]
@nevets963 Done! The upgrade worked on my device.

Inspired from: https://github.com/getumbrel/umbrel-apps/blob/9e2756aee9088d2639a95c94eafc9cb9c896594a/nextcloud/hooks/pre-start

**Review by nevets963 — COMMENTED** [review]
@woofbotapp Nice work with the pre-start hook - it works perfectly.

I forgot to mention that support for hooks came in with the manifest version `1.1`. Can you bump that to `1.1` in your `umbrel-app.yml`?

Otherwise, this is tested on `arm64` and `amd64`.

**Comment by woofbotapp** [comment]
bumped

**Review by nevets963 — APPROVED** [review]
Tested one more time on my side.

Everything looks good. Merging now 🚀

**Pull request merged**
