### PR TITLE
nutstash version 0.1.12

### PR DESCRIPTION
**Pull request by gandlafbtc**
I'm trying to introduce a feature to sync tokens with the umbrel server. It's still not completely working. I think the issue is that i need write access to the host system to have a persistent volume. 

The rest should work fine, but I would like to fix that before merging the new version. 

Maybe you guys have a good idea how to solve this @nmfretz ? I'm pretty dumb at docker

### CODE REVIEW

**Comment by nmfretz** [comment]
Sorry for the delay @gandlafbtc. I'll take a look at this tomorrow so we can get this update out the door!

I too used to be pretty dumb at docker. Now I am only fairly dumb at docker.

**Comment by gandlafbtc** [comment]
Thanks for your work on this! I have had some other things pending, but I will work on this again next week. I will dive into it on monday. Also sorry for the delayed reply on my side.

I have just skimmed through your comments, but i think this helps a ton, and im fairly certain we can push the update out before next weekend. Then I can also include all the latest features with the next update.

I will look into options for avoiding the need for an app restart.

**Comment by nmfretz** [comment]
Hey @gandlafbtc, are you okay if I close this old draft PR? We can reopen down the line if you get back to working on it at some point.

**Comment by nmfretz** [comment]
@gandlafbtc I see nutstash is now on v0.2.7 https://github.com/gandlafbtc/nutstash-wallet/releases/tag/0.2.7

Let's close this old 0.1.12 PR. Please ping me whenever you're ready for an update 🌰

**Pull request closed without merging**
