### PR TITLE
Update LN Markets to v1.2.4

### PR DESCRIPTION
**Pull request by kibotrel**
Patchnote [v1.2.4](https://github.com/ln-markets/umbrel/releases/tag/v1.2.4)

Related PRs: https://github.com/getumbrel/umbrel-apps-gallery/pull/14

### CODE REVIEW

**Comment by kibotrel** [comment]
I need to fix CORS once again due to the proxy

**Comment by louneskmt** [comment]
Tested and working on `amd64`. Will try on `arm64` soon.

**Comment by kibotrel** [comment]
Tested on `arm64` with the LIghtning Node version `0.15.2-beta`.

**Comment by louneskmt** [comment]
Tested and working on `arm64` as well, LGTM @nevets963 :)

**Pull request closed without merging**
