### PR TITLE
Update syncthing to version 1.28.1

### PR DESCRIPTION
**Pull request by al-lac**
Tested on Raspberry Pi 5.

### CODE REVIEW

**Comment by al-lac** [comment]
Duplicate of #1897

**Comment by nmfretz** [comment]
Ah, sorry @al-lac I missed this before running our auto-updater script, which updated syncthing: https://github.com/getumbrel/umbrel-apps/pull/1897

**Comment by nmfretz** [comment]
haha, you beat me to closing this by a second

**Comment by al-lac** [comment]
I am on a roll today :-D

**Pull request closed without merging**
