### PR TITLE
Update Immich to v1.75.2

### PR DESCRIPTION
**Pull request by ankit5902**
I've updated image to v1.75.2 for

- `immich-server` (the same `immich-server` tag is used under `server` and `microservices`)
- `immich-machine-learning`
- `immich-web`
- `immich-proxy`

Did not change `typesense:0.24.1`, `redis:6.2-alpine` or `postgres:14-alpine`

### CODE REVIEW

**Comment by ankit5902** [comment]
In Immich, a new capability has been introduced: `hardware acceleration`. This feature allows the utilization of hardware resources to enhance video transcoding processes. 

However, I'm not sure how to integrate this feature into Umbrel. The reason is that Umbrel's user base consists of individuals with varying hardware configurations; some may have GPUs, while others may not. Moreover, these GPUs might be from different manufacturers such as NVIDIA, Intel with QuickSync, or systems that support VAAPI in WSL2.

**Comment by ankit5902** [comment]
To enable this, users are required to uncomment the below lines from the `docker-compose.yml` file within the `immich-microservices` section.

```
# extends:
#   file: hwaccel.yml
#   service: hwaccel
```

After that, within the `hwaccel.yml` file, users should uncomment lines based on their specific hardware setup, such as Intel QuickSync, VAAPI, or NVIDIA GPU.

```
version: "3.8"

# Hardware acceleration for transcoding - Optional
# This is only needed if you want to use hardware acceleration for transcoding.
# Depending on your hardware, you should uncomment the relevant lines below.

services:
  hwaccel:
    # devices:
    #   - /dev/dri:/dev/dri  # If using Intel QuickSync or VAAPI
    # volumes:
    #   - /usr/lib/wsl:/usr/lib/wsl # If using VAAPI in WSL2
    # environment:
    #   - NVIDIA_DRIVER_CAPABILITIES=all # If using NVIDIA GPU
    #   - LD_LIBRARY_PATH=/usr/lib/wsl/lib # If using VAAPI in WSL2
    #   - LIBVA_DRIVER_NAME=d3d12 # If using VAAPI in WSL2
    # deploy: # Uncomment this section if using NVIDIA GPU
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu,video]
```

**Comment by nmfretz** [comment]
Thanks @ankit5902 for the thorough PR!

> However, I'm not sure how to integrate this feature in Immich on Umbrel. The reason is that Umbrel's user base consists of individuals with varying hardware configurations; some may have GPUs, while others may not. Moreover, these GPUs might be from different manufacturers such as NVIDIA, Intel with QuickSync, or systems that support VAAPI in WSL2.

Good summary of the difficulties 👌. I noticed the new hardware acceleration option when we were doing the 1.74.0 update, but opted to not include it for the reasons you noted above. The idea for all apps on Umbrel is to have them be one-click install, and then any configuration can be done via the web UI of the app. Immich is under such rapid development that these early features require manual configuration... hopefully in the future they will allow for full configuration via the UI. It could be a good idea for us to open an issue in their repo letting them know that config via UI would be amazing.

For now, let's hold off trying to implement this. Sufficiently advanced (and curious users) can always modify their compose and config files to play around with hardware acceleration.

**Comment by nmfretz** [comment]
I made a slight tweak to the breaking changes wording in the release notes, since it doesn't apply to Umbrel users who just install the app and don't mess around with the compose file.

Tested on arm64 and amd64. Going live 📸. Again, fantastic work!

**Comment by mateosilguero** [comment]
Idk if its related, but after this update, my umbrel servel is shuting down constantly (raspi 4).

**Pull request merged**
