### PR TITLE
Update itchsyats organisation to 10101

### PR DESCRIPTION
**Pull request by bonomat**
We renamed the itchysats organization to 10101.

### CODE REVIEW

**Comment by nevets963** [comment]
@bonomat Do you also want to update any fields in the app manifest (`umbrel-app.yml`)? Eg. the `developer` field? https://github.com/getumbrel/umbrel-apps/blob/048b937ebdbd3aceb82b0771aab433e1bd7e3fa9/itchysats/umbrel-app.yml#L49

**Comment by bonomat** [comment]
> @bonomat Do you also want to update any fields in the app manifest (`umbrel-app.yml`)? Eg. the `developer` field?
> 
> https://github.com/getumbrel/umbrel-apps/blob/048b937ebdbd3aceb82b0771aab433e1bd7e3fa9/itchysats/umbrel-app.yml#L49

thanks for pointing it out, I'll do that in a sec

**Comment by bonomat** [comment]
@nevets963 : done :)

**Comment by nevets963** [comment]
@bonomat I can't checkout this PR, could you also update the `submitter` field?

**Review by nevets963 — APPROVED** [review]
@bonomat Thanks for updating the other fields.

Tested on `arm64` and `amd64`.

Merging now 😄

**Comment by bonomat** [comment]
awesome, thanks :)

**Pull request merged**
