### PR TITLE
update btcpay

### PR DESCRIPTION
**Pull request by Kukks**

### CODE REVIEW

**Comment by dungvanphan** [comment]
bc1qw400kjxesm5ekgwsl77cu33l9k2t95ezscgx9u

**Comment by ParthJadhav** [comment]
Hey @Kukks , Thanks a lot for the update. I'll test out the update as soon as my Bitcoin node is done synchronising.

**Review by ParthJadhav — APPROVED** [review]
Tested on Digital Ocean `x86_64` works nice.

What did I test:
- Created a wallet on BTC Pay Server
- Sent BTC to the wallet from Binance
- Upgraded BTC Pay server to `1.11.6` 🔼
- Sent BTC back to Binance wallet

**Comment by nmfretz** [comment]
Thanks for the update @Kukks, and for the review/testing @ParthJadhav.

I pushed [ec541ee](https://github.com/getumbrel/umbrel-apps/pull/789/commits/ec541ee8f81455a5e49796e5c46903dfb7d16cb5) to use the multi-arch digest for `btcpayserver/btcpayserver`. The previous commit was using the amd64-specific digest which won't work for arm users.

Tested on arm64 and x86(amd64). Merging.

**Comment by dungvanphan** [comment]
#98148

**Comment by dungvanphan** [comment]
bc1qxcaftt9wq2e9vsactc26lylx5vurve5cw285k6

**Pull request merged**
