### PR TITLE
App Submission: Joplin Server

### PR DESCRIPTION
**Pull request by danvergara**
# App Submission

### App name
Joplin Server

### 256x256 SVG icon

[https://void.cat/NF1f95ZbQAy9eQy5YrCouC](https://void.cat/NF1f95ZbQAy9eQy5YrCouC)

### Gallery images

[https://void.cat/HGrQV4qJfN8K4u5EJyrS7J](https://void.cat/HGrQV4qJfN8K4u5EJyrS7J)
[https://void.cat/qxFRwcZ6Z7BKqNEGvGgHA](https://void.cat/qxFRwcZ6Z7BKqNEGvGgHA)
[https://void.cat/Us5fS4hWCEqwnLS2PGTXcH](https://void.cat/Us5fS4hWCEqwnLS2PGTXcH)

### I have tested my app on:
- [ ] [Umbrel dev environment](https://github.com/getumbrel/umbrel-dev)
- [ ] [Umbrel OS on a Raspberry Pi 4](https://github.com/getumbrel/umbrel-os)
- [x] [Custom Umbrel install on Linux](https://github.com/getumbrel/umbrel#-installation)

I had to get the current host public IP to set the  `APP_BASE_URL` env var as a public URL. My solution is a little bit hacky  and I think it can be done using Nginx, but I don't know how to do it, since we don't have a fixed domain for every installation.

### CODE REVIEW

**Comment by danvergara** [comment]
Thanks for the support @nmfretz . Let me test this out over the weekend ot make sure it works as expected.

**Comment by danvergara** [comment]
@nmfretz I think this is ready for review, but I have a little concern with my current approach.

**Comment by danvergara** [comment]
I experimented with nginx but was pointless, adding a public URL/IP is mandatory for some odd reason that should be out of the scope of Joplin's configuration.

@nmfretz I think this is ready for review. If you have comments or questions or suggestions, let me know and I'll be more than happy to address them.

**Comment by danvergara** [comment]
This is not working when the request is coming through the Tor network. Is there a way to tell when this happens to properly set the APP_BASE_URL  variable with the value of $TOR_PROXY_IP dynamically?

**Comment by nmfretz** [comment]
Thanks for your hard work in submitting Joplin @danvergara. I just started reviewing, but noticed that the [joplin/server Docker images](https://hub.docker.com/r/joplin/server/tags) are **only** available for the amd64 architecture. This means that the app will break for users who run Umbrel on an arm device like a Raspberry Pi. We cannot accept any app that doesn't work on both arm64 and amd64.

I found [this closed issue](https://github.com/laurent22/joplin/issues/5932) on the Joplin GitHub that requested an arm64 image, but it didn't get any traction. I think the best bet is to be vocal on Joplin's GitHub about them building and pushing multi-arch images to Docker Hub.

**Comment by nmfretz** [comment]
@danvergara I am closing this issue for now since there is no multi-arch docker image. I have added my voice to this Joplin issue here https://github.com/laurent22/joplin/issues/5932. Let's keep an eye on this and reopen if a multi-arch image gets built.

**Pull request closed without merging**
