### PR TITLE
Update Immich to v1.72.2

### PR DESCRIPTION
**Pull request by ankit5902**
I've updated the image to v1.72.2 for

`immich-server` (the same immich-server tag is used under `server` and `microservices`)
`immich-machine-learning`
`immich-web`
`immich-proxy`

I did not change `typesense:0.24.1`, `redis:6.2-alpine` or `postgres:14-alpine`

### CODE REVIEW

**Comment by ankit5902** [comment]
**⚠️ Breaking Changes**
- The mobile app needs to be on the same version of the server to operate correctly 
- Drop support for armV7 architecture
 
This update introduces many new features to Immich since the last Umbrel update of v1.65, with numerous updates to Immich since then.

Full release notes can be found at: https://github.com/immich-app/immich/releases

**Comment by ankit5902** [comment]
Hey @nmfretz this is ready for review. Please check and let me know if something needs to be changed.

**Comment by 0ceanSlim** [comment]
Perfect I was waiting on this!

**Comment by nmfretz** [comment]
Phenomenal work @ankit5902! Thank you for catching the change to the compose file and for customizing the release notes to include relevant changes from the skipped versions.

I have tested on arm64 x86(amd64) and made some very minor changes to the release notes. Going live.

**Comment by swarupbhc** [comment]
@ankit5902 there is another version released, can you please update that too?

**Pull request merged**
