### PR TITLE
App Submission: Passky Server

### PR DESCRIPTION
**Pull request by zigazajc007**
# App Submission

### App name
Passky Server

### 256x256 SVG icon
_(Submit an icon with no rounded corners as it will be dynamically rounded with CSS. GitHub doesn't allow uploading SVGs directly, so please upload your icon to an alternate service, like https://svgur.com, and paste the link below.)_

https://svgshare.com/i/eSC.svg

### Gallery images
_(Upload 3 to 5 high-quality gallery images (1440x900px) of your app in PNG format, or just upload 3 to 5 screenshots of your app and we'll help you design the gallery images.)_

Screenshot

Screenshot2

Screenshot3

Screenshot4

Screenshot5

### I have tested my app on:
- [ ] [Umbrel dev environment](https://github.com/getumbrel/umbrel-dev)
- [ ] [Umbrel OS on a Raspberry Pi 4](https://github.com/getumbrel/umbrel-os)
- [x] [Custom Umbrel install on Linux](https://github.com/getumbrel/umbrel#-installation)

### CODE REVIEW

**Comment by zigazajc007** [comment]
- SQLite support has been added to Passky Server, so now it can be provided with only one container.
- Secure Cookies has also been disabled so now Admin Panel works on http

**Comment by nevets963** [comment]
@zigazajc007 Thanks for re-submitting Pasky server and Client into the Umbrel App Store! I see it's marked as Open; is everything ready for me to check it over and test?

**Comment by zigazajc007** [comment]
Everything seems to be ready.

**Review by nevets963 — COMMENTED** [review]
@zigazajc007 I've just took Passky Server (and Client) for a spin.

I can see the level of attention gone into this app; it's really nicely made!

I did note this tab when not logged in:
Screenshot 2023-02-02 at 23 48 10

I feel uneasy about this because we have the App Proxy's authentication disabled, and we're (potentially) exposing sensitive details about the system, their accounts and Passky's version. It seems like this would be better to have protected using the admin account?

**Comment by zigazajc007** [comment]
> @zigazajc007 I've just took Passky Server (and Client) for a spin.
> 
> I can see the level of attention gone into this app; it's really nicely made!
> 
> I did note this tab when not logged in: Screenshot 2023-02-02 at 23 48 10
> 
> I feel uneasy about this because we have the App Proxy's authentication disabled, and we're (potentially) exposing sensitive details about the system, their accounts and Passky's version. It seems like this would be better to have protected using the admin account?

Hello,

Passky password manager is focused on privacy and also transparency. So 3 API endpoints for statistics are open to everyone.

**getInfo endpoint** returns version, number of accounts registered, number of passwords stored, maximum amount of accounts that can be created on this server, bcrypt hashing cost, default amount of passwords that each account can store and country (Country is determined thru ENV variable and by default US is used). 

Those information could help users choose Passky Server and will know how many passwords they are allowed to store even before they create the account.

image

**getStats endpoint** returns processor used, memory used, memory total, disk used, disk total information. This would allow monitoring your Passky instance even without using 3rd party software.

By default number of threads is set to 1, that's why you can see 173% of cpu consumed on your image. If you want to see cpu usage from 0 to 100% you can set the right amount of threads with ENV variable.

image

**getReport endpoint** returns amount of active users (Amount of accounts logged in, in the last 7 days) and number of accounts created each day. So with those numbers we can create a graph of user growth.

image

None of those 3 public API endpoints exposes personal data, but it can help users a lot when choosing the right Passky Server to use.

**getInfo endpoint**: https://eu.passky.org/?action=getInfo
**getStats endpoint**: https://eu.passky.org/?action=getStats
**getReport endpoint**: https://eu.passky.org/?action=getReport

**Comment by nevets963** [comment]
@zigazajc007 I was concerned that should there ever be a CVE for `Passky Server 8.1.2`, then having versioning like this more easily explosed may make an attack 1 step easier. However, if this telemetry is core to your app, then I'm not going to block this PR.

**Review by nevets963 — APPROVED** [review]

**Comment by zigazajc007** [comment]
Transparency is important only for our public Passky Servers. So those API endpoints can also be disabled by default on Umbrel / for self-hosters.

**Comment by nevets963** [comment]
@zigazajc007 Looks like we're go for launch. We've prepared the graphics for the App Store located here: https://github.com/getumbrel/umbrel-apps-gallery/pull/35. If you're happy with that, then we'll get everything merged and live into the App Store 😄

**Comment by zigazajc007** [comment]
Everything looks great.

Thanks.

**Comment by nevets963** [comment]
This will appear in the Umbrel App Store in about 5 minutes 🚀 Congrats on the launch! 😄

**Pull request merged**
