### PR TITLE
App Submission: autobrr

### PR DESCRIPTION
**Pull request by fabricionaweb**
# App Submission

### autobrr
[autobrr](https://autobrr.com/introduction) is the modern download automation tool for torrents and usenet

### 256x256 SVG icon
https://raw.githubusercontent.com/autobrr/autobrr/master/web/src/logo.svg

### Gallery images
img-1
img-2

### I have tested my app on:
- [ ] [Umbrel dev environment](https://github.com/getumbrel/umbrel-dev)
- [ ] [Umbrel OS on a Raspberry Pi 4](https://github.com/getumbrel/umbrel-os)
- [ ] [Custom Umbrel install on Linux](https://github.com/getumbrel/umbrel#-installation)

### CODE REVIEW

**Comment by ParthJadhav** [comment]
Also, Feel free to add:

```
submitter: yourName
submission: thisPrUrl
```

so that your name is visible on the app store. [Example](https://github.com/getumbrel/umbrel-apps/blob/master/btc-rpc-explorer/umbrel-app.yml#L48-L49)

**Review by ParthJadhav — APPROVED** [review]
Tested it on `umbrel-dev` server, and it runs properly.
note: didn't test the actual functionality because I didn't understand the app.

Looks good except the optional changes I've mentioned above.

**Comment by fabricionaweb** [comment]
Thank you very much for the testing! I'll apply the mentioned changes

**Comment by ParthJadhav** [comment]
Thanks for the Contribution @fabricionaweb ❤️

**Comment by nmfretz** [comment]
Excellent, thank you for this submission @fabricionaweb, we really appreciate it! Tested on both arm64 and x86(amd64). We are just getting the icon and gallery images ready now and will send this to the app store shortly.

FYI, I bumped the version to the recently released v1.31.0 and also renamed the bind mount on the host to `${APP_DATA_DIR}/data` purely so that it is consistent with other apps on Umbrel (your way was working just fine).

**Comment by nmfretz** [comment]
Alrighty, icon and gallery images have been added: https://github.com/getumbrel/umbrel-apps-gallery/commit/e32c7152014941c31e86ba7fb78b55e1254f800a. Going live to the app store now 🐇.

Thanks again for all your work on this @fabricionaweb! This is a wonderful addition.

**Pull request merged**
