### PR TITLE
App Submission: WikiJS

### PR DESCRIPTION
**Pull request by IMPranshu**
# App Submission

### WikiJS
...

### 256x256 SVG icon
https://github.com/IMPranshu/svg-logo/blob/main/wiki.svg

...

### Gallery images
wiki
Screenshot from 2022-11-11 01-24-20
Screenshot from 2022-11-11 01-25-55
Screenshot from 2022-11-11 01-26-36

...

### I have tested my app on:
- [ ] [Umbrel dev environment](https://github.com/getumbrel/umbrel-dev)
- [x] [Umbrel OS on a Raspberry Pi 4](https://github.com/getumbrel/umbrel-os)
- [x] [Custom Umbrel install on Linux](https://github.com/getumbrel/umbrel#-installation)

### CODE REVIEW

**Review by nevets963 — APPROVED** [review]
@IMPranshu Thanks for submitting WikiJS! We appreciate your efforts that went into this PR!

Tested on `arm64` and `amd64`.

@mayankchhabra the App Proxy's default configuration will lock-down this app and therefore this will behave like a private Wiki (which maybe desirable). However, given this has it's own auth. system and this type of application is usually about sharing data/info, it seems like we should the App Proxy off by default for WikiJS. Thoughts?
We'll help need your help here again with App Store graphics :)

However in its current form, this is approved from me.

Once graphics assets are merged, I'll run another test and then merge this in.

**Comment by mayankchhabra** [comment]
Thanks again for another solid app submission, @IMPranshu!

> the App Proxy's default configuration will lock-down this app and therefore this will behave like a private Wiki (which maybe desirable). However, given this has it's own auth. system and this type of application is usually about sharing data/info, it seems like we should the App Proxy off by default for WikiJS.

Sounds good, agree with your reasoning! We can turn it off.

**Comment by nevets963** [comment]
Gallery assets are located here: https://github.com/getumbrel/umbrel-apps-gallery/pull/28 Will start on final tests today before merging.

**Comment by nevets963** [comment]
Great work all round everyone! And Happy Holidays! Merging now 🚀

**Comment by kszere** [comment]
How update Wiki.JS to v2.5.300?

**Comment by Niclassslua** [comment]
image

<br><br>

Compared to other App Icons the WikiJS icon is very low quality.

I would suggest using the one I uploaded. It's 900x900.

<br><br>

wikijs

**Pull request merged**
