### PR TITLE
Update LNDg to v1.6.1

### PR DESCRIPTION
**Pull request by cryptosharks131**
Updates LNDg to v1.6.1
https://github.com/cryptosharks131/lndg/releases/tag/v1.6.1
https://github.com/cryptosharks131/lndg/pkgs/container/lndg/82690937?tag=v1.6.1

Fixes a breaking change introduced in a recent `pandas` update which causes new installs and updates to fail.

### CODE REVIEW

**Comment by nmfretz** [comment]
Checking this on priority now. v1.6.0 that I tested about 7 hours ago today did not fail on updates or new installs. Did this `pandas` update just hit?

**Comment by nmfretz** [comment]
Okay, tested on arm64 and amd64. Going live.

**Comment by pjw65** [comment]
unfortunately auto fees are not updating fees any more (still suggest a value, but not update in 1 hour, as I selected).

**Comment by cryptosharks131** [comment]
Another release `v1.6.3` will be coming shortly and contains fixes for this and another reported issue.

**Pull request merged**
