### PR TITLE
Upgrade Pi-Hole to 2022.05

### PR DESCRIPTION
**Pull request by kroese**

### CODE REVIEW

**Comment by mccolister1017** [comment]
pi-hole is already up to date .

**Comment by mccolister1017** [comment]
> @mccolister1017 How do you mean? This upgrades version 2022.04.3 to 2022.05.

haaaa! my  bad april to may oh ok

**Review by nevets963 — APPROVED** [review]
Thank you for the PR!

Tested on AMD64 and ARM (Pi).

@kroese Approved from me.

@lukechilds Can you have a final check over?

**Comment by lukechilds** [comment]
Looks great, thanks @kroese!

**Pull request merged**
