### PR TITLE
App Submission: Mumble

### PR DESCRIPTION
**Pull request by olwe1**

### CODE REVIEW

**Review by 404Nikhil — APPROVED** [review]

**Review by nevets963 — COMMENTED** [review]
@olwe1 Thanks a huge amount for submitting Mumble into the Umbrel App Store!

I've patched/cleaned up a couple of things in the PR. For example, some simplification with no longer needing a `exports.sh` file.

When I tried to test Mumble, I see these errors from the container logs:
```
<X>2022-10-21 03:01:42.719 SSL: OpenSSL version is 'OpenSSL 1.1.1q  5 Jul 2022'
<F>2022-10-21 03:01:42.719 Specified ini file /data/mumble-server.ini could not be opened
<X>2022-10-21 03:01:46.592 SSL: OpenSSL version is 'OpenSSL 1.1.1q  5 Jul 2022'
<F>2022-10-21 03:01:46.592 Specified ini file /data/mumble-server.ini could not be opened
<X>2022-10-21 03:01:53.760 SSL: OpenSSL version is 'OpenSSL 1.1.1q  5 Jul 2022'
<F>2022-10-21 03:01:53.761 Specified ini file /data/mumble-server.ini could not be opened
<X>2022-10-21 03:02:07.344 SSL: OpenSSL version is 'OpenSSL 1.1.1q  5 Jul 2022'
<F>2022-10-21 03:02:07.345 Specified ini file /data/mumble-server.ini could not be opened
```

Is perhaps a default config .ini file missing from this PR? Or should Mumble be told to use an .ini file that is already somewhere in the Docker image?

**Comment by olwe1** [comment]
Yes the `mumble-server.ini` is in the Docker image in `/data`. I have no errors when running the image with a simple `docker run`.
Maybe it's an ownership issue.
Here's the repo of the Dockerfile: [](https://git.olwe.link/olwe/mumble-docker/src/branch/master)

**Comment by olwe1** [comment]
Yes, the user might want to change some config through this file. Do you know a way to use the file from the image and not the other way around ? Otherwise we could just add the `mumble-server.ini` file to this PR.

**Comment by nevets963** [comment]
No, this is simply how mounts work; where the host is the 'source of truth'. We can simply include the `mumble-server.ini` file in this PR (inside the `data` directory).

**Comment by olwe1** [comment]
I was taking a look at the gitea `data` folder [here](https://github.com/getumbrel/umbrel-apps/tree/master/gitea). There's nothing inside it and when docker run the image a config file is shared on that folder. Used by the container and editable on the host.

**Comment by nevets963** [comment]
I couldn't find atm how gitea is specifically doing it, but they usually have an entrypoint script or have logic baked into their binary similar to this:
```
if not fs.exists("/data/settings.conf"):
    fs.writeFile("/data/settings.conf",  { ... default settings ... })

./myapp -c /data/settings.conf
```
Here is a real world example from nitter: https://github.com/ceramicwhite/umbrel-patch-ci/blob/a2dceb2e3491b26031e9b24caf75d6d6a385a889/nitter/patched-files/entrypoint.sh#L28-L44

**Comment by nevets963** [comment]
Ok, I got the container to now start, but I am now getting these errors from the container logs:

```
<W>2022-10-25 10:12:07.267 1 => Server listening on 0.0.0.0:64738
<W>2022-10-25 10:12:07.859 1 => Generating new server certificate.
<W>2022-10-25 10:12:07.955 1 => Registering zeroconf service...
<W>2022-10-25 10:12:07.955 Zeroconf: Third-party API reports error -65537, service registration probably failed
<W>2022-10-25 10:12:07.977 1 => Not registering server as public
<W>2022-10-25 10:12:07.985 1 => <0:(-1)> New connection: 10.21.0.8:60054
<W>2022-10-25 10:12:08.002 1 => <0:(-1)> Connection closed: The remote host closed the connection [1]
<W>2022-10-25 10:12:21.255 1 => <0:(-1)> New connection: 10.21.0.8:43002
<W>2022-10-25 10:12:21.267 1 => <0:(-1)> Connection closed: Error during SSL handshake: error:1408F09C:SSL routines:ssl3_get_record:http request [13]
<W>2022-10-25 10:12:21.456 1 => <0:(-1)> New connection: 10.21.0.8:43016
<W>2022-10-25 10:12:21.467 1 => <0:(-1)> Connection closed: Error during SSL handshake: error:1408F09C:SSL routines:ssl3_get_record:http request [13]
<W>2022-10-25 10:12:22.463 1 => <0:(-1)> New connection: 10.21.0.8:43024
<W>2022-10-25 10:12:22.476 1 => <0:(-1)> Connection closed: Error during SSL handshake: error:1408F09C:SSL routines:ssl3_get_record:http request [13]
<W>2022-10-25 10:12:22.637 1 => <0:(-1)> New connection: 10.21.0.8:43038
<W>2022-10-25 10:12:22.646 1 => <0:(-1)> Connection closed: Error during SSL handshake: error:1408F09C:SSL routines:ssl3_get_record:http request [13]
<W>2022-10-25 10:12:22.786 1 => <0:(-1)> New connection: 10.21.0.8:43044
<W>2022-10-25 10:12:22.794 1 => <0:(-1)> Connection closed: Error during SSL handshake: error:1408F09C:SSL routines:ssl3_get_record:http request [13]
<W>2022-10-25 10:12:49.899 1 => <0:(-1)> New connection: 10.21.0.8:43972
<W>2022-10-25 10:12:49.908 1 => <0:(-1)> Connection closed: Error during SSL handshake: error:1408F09C:SSL routines:ssl3_get_record:http request [13]
<W>2022-10-25 10:12:50.136 1 => <0:(-1)> New connection: 10.21.0.8:43974
<W>2022-10-25 10:12:50.146 1 => <0:(-1)> Connection closed: Error during SSL handshake: error:1408F09C:SSL routines:ssl3_get_record:http request [13]
<W>2022-10-25 10:12:50.291 1 => <0:(-1)> New connection: 10.21.0.8:43988
<W>2022-10-25 10:12:50.304 1 => <0:(-1)> Connection closed: Error during SSL handshake: error:1408F09C:SSL routines:ssl3_get_record:http request [13]
<W>2022-10-25 10:12:50.435 1 => <0:(-1)> New connection: 10.21.0.8:44000
<W>2022-10-25 10:12:50.446 1 => <0:(-1)> Connection closed: Error during SSL handshake: error:1408F09C:SSL routines:ssl3_get_record:http request [13]
<W>2022-10-25 10:12:50.556 1 => Ignoring connection: 10.21.0.8:44008 (Global ban)
<W>2022-10-25 10:12:50.704 1 => Ignoring connection: 10.21.0.8:44012 (Global ban)
<W>2022-10-25 10:12:51.985 1 => Ignoring connection: 10.21.0.8:44026 (Global ban)
<W>2022-10-25 10:12:52.098 1 => Ignoring connection: 10.21.0.8:44030 (Global ban)
<W>2022-10-25 10:12:52.235 1 => Ignoring connection: 10.21.0.8:44042 (Global ban)
<W>2022-10-25 10:12:52.406 1 => Ignoring connection: 10.21.0.8:44056 (Global ban)
<W>2022-10-25 10:12:52.510 1 => Ignoring connection: 10.21.0.8:44060 (Global ban)
<W>2022-10-25 10:13:01.966 1 => Ignoring connection: 10.21.0.8:42132 (Global ban)
```

All apps have their traffic proxied through our app proxy that adds some additional layers of security. Do you have some restrictions for upstream proxies? And also, does this application except only HTTPS connections?

**Comment by olwe1** [comment]
I don't think so for both questions. There's a mention for proxies [in the config file](https://git.olwe.link/olwe/mumble-docker/src/branch/master/mumble-server.ini#L424), by default there's no limit.

For the SSL handshake part I don't find anything about a HTTPS restriction.

For the last logs (Global ban), there's an auto-ban feature to avoid spams: [conf file](https://git.olwe.link/olwe/mumble-docker/src/branch/master/mumble-server.ini#L379). In this case, the app-proxy might be considered as a spammer.

**Comment by nevets963** [comment]
@olwe1 After digging into how Mumble works a bit more. I think I see now how this works. I believe ports `64738/TCP` and `64738/UDP` have to be open for Mumble clients to connect to. So you would run a Mumble client on your PC and connect your client to the Mumble server (using those open ports) running on your Umbrel right?

And if so, there is then no Web UI included in the Mumble server?

**Comment by nevets963** [comment]
Yh, I think it makes sense to show any relevant statuses and as you say the logs of the server. In the case of snowflake it's particularly useful where it's showing usage and not just internal logs. If Mumble has something similar, then that is usually helpful for users.

**Comment by nevets963** [comment]
@olwe1 Just a friendly ping to see if this PR will still progress? I think what is remaining is a UI app to show the logs for the server. The snowflake app in the app store is a pure server/backend process where the UI is simply 'tailing' a log file - I think that would be good enough here right? If so, we could use a gotty container to show the streaming logs.

**Comment by olwe1** [comment]
Hopefully yes, I can't find the time lately but I started to create a simple log page like snowflake. I'll try to find some time in january.

**Comment by olwe1** [comment]
Woops I forgot you did some changes on this PR and just force pushed my changes... Sorry about that.
I added an HTML file with logs and reworked the docker image to suits my needs. I didn't test it yet since I have to setup the dev environnement.

**Comment by nmfretz** [comment]
Hi @olwe1, I am closing this PR for now due to inactivity, but please don't hesitate to reopen if/when you want to keep working on Mumble!

**Pull request closed without merging**
