### PR TITLE
App Submission: Grafana

### PR DESCRIPTION
**Pull request by phelipebf**
# App Submission

### Grafana
...

### 256x256 SVG icon

https://svgur.com/s/1BeX

### Gallery images

- https://grafana.com/static/img/grafana/showcase_visualize.jpg
- https://grafana.com/media/products/cloud/grafana/grafana-dashboard-english.png
- https://grafana.com/media/products/cloud/grafana/grafana-kubernetes.jpg
- https://grafana.com/static/img/grafana/time_series_light_theme_sized.png
- https://grafana.com/static/img/grafana/stat_light_theme_sized.png
- https://grafana.com/static/img/grafana/gauge_light_theme_sized.png

### I have tested my app on:
- [x] umbrelOS on a Raspberry Pi
- [ ] umbrelOS on an Umbrel Home
- [x] umbrelOS on Linux VM

### CODE REVIEW

**Comment by nmfretz** [comment]
Thanks for submitting Grafana @phelipebf! We've got this on our radar and will review soon.

**Comment by phelipebf** [comment]
@sharknoon thank you for the suggestions. I've made the changes and updated the PR.

**Comment by nmfretz** [comment]
Excellent, thanks @phelipebf! I have tested and this is working great. We will get the icon and gallery assets made up and then we can go live to the app store.

**Comment by nmfretz** [comment]
Gallery assets are [done](https://github.com/getumbrel/umbrel-apps-gallery/tree/master/grafana). Thanks again for the excellent submission @phelipebf! Going live.

image

**Pull request merged**
