### PR TITLE
App Submission - Mealie

### PR DESCRIPTION
**Pull request by nmfretz**
https://mealie.io/
https://github.com/hay-kot/mealie

Mealie is a self hosted recipe manager and meal planner. Easily add recipes by providing the url and Mealie will automatically import the relevant data or add a family recipe with the UI editor. Mealie also provides an API for interactions from 3rd party applications.

### CODE REVIEW

**Comment by nmfretz** [comment]
Tested on arm64 and amd64. Going live 🍔

**Comment by PlebeiusGaragicus** [comment]
Is Umbrel's implementation open-source?  From what I understand, the Umbrel "app store" pulls down the appropriate docker images and spins them up, but is Umbrel's port of this open-source repo itself open-source?

**Comment by Macenstine** [comment]
Hey is there a reason this is still using the 1.0.0beta-5 release when v1.2.0 is out?

**Comment by PlebeiusGaragicus** [comment]
Seems like the Umbrel "app store" is having trouble maturing due to heavy centralization; they're bottlenecked.  This is not the open platform you're looking for.

**Pull request merged**
