### PR TITLE
App Submission: Firefox Browser

### PR DESCRIPTION
**Pull request by IMPranshu**
# App Submission

### Firefox
...

### 256x256 SVG icon
https://github.com/IMPranshu/svg-logo/blob/main/firefox-logo.svg

...

### Gallery images
Screenshot from 2022-11-04 23-06-01
Screenshot from 2022-11-04 23-06-10
Screenshot from 2022-11-04 23-06-52
Screenshot from 2022-11-04 23-10-52

...

### I have tested my app on:
- [ ] [Umbrel dev environment](https://github.com/getumbrel/umbrel-dev)
- [x] [Umbrel OS on a Raspberry Pi 4](https://github.com/getumbrel/umbrel-os)
- [x] [Custom Umbrel install on Linux](https://github.com/getumbrel/umbrel#-installation)

### CODE REVIEW

**Review by nevets963 — APPROVED** [review]
@IMPranshu Many thanks for submitting Firefox into the Umbrel App Store!

I've actually had to use this a few times when testing other apps haha 😄 

Tested on `arm64` and `amd64`.

Approved from me 🚀 

@mayankchhabra Can you help us prepare gallery assets for the app store please?

Once these assets have been merged in, I'll do 1 final test and then this will get merged in too.

**Comment by nevets963** [comment]
Gallery assets are located here: https://github.com/getumbrel/umbrel-apps-gallery/pull/23 Will start on final tests today before merging.

**Comment by nevets963** [comment]
As I final test, I managed to access Firefox on my cloud-based Umbrel inside Firefox running on my home-Umbrel running inside Firefox on my laptop 😆  Merging now 🚀

**Comment by IMPranshu** [comment]
> As I final test, I managed to access Firefox on my cloud-based Umbrel inside Firefox running on my home-Umbrel running inside Firefox on my laptop 😆  Merging now 🚀 

Woah!!!! Truly "INCEPTION" and this time decentralised.

**Pull request merged**
