### PR TITLE
Update pocketbase to version v0.23.11

### PR DESCRIPTION
**Pull request by nmfretz**
🤖 This is an automated pull request to update pocketbase to version v0.23.11. This PR must be reviewed and tested before merging.

### CODE REVIEW

**Comment by nmfretz** [comment]
🤖 This is an automated summary of installation tests for pocketbase:

- ✅ App successfully installed in umbrel-dev instance
- ✅ App successfully listed in umbrel.yaml
- ✅ App UI successfully returns a 200 status code
- 📸 Screenshot of the app:
  App Screenshot

**This PR must still be reviewed and tested before merging.**

**Comment by al-lac** [comment]
Hey @nmfretz, just so you know, v0.23.12 is already out. 

One more thing, I tried the app today. There seems to be a bug starting with v0.23 that does not allow simple creation of the first admin: muchobien/pocketbase-docker#28

The only way I found so far is to access the troubleshooting menu and copy the URL to create the first admin.

Also tried it with a post-install hook like this, but even though it says it created an admin, it does not work:
```bash
#!/usr/bin/env bash
set -euo pipefail

/usr/local/bin/pocketbase superuser upsert umbrel@umbrel.local umbrel-pocketbase
```

Maybe some Info in the description would be good until this is solved upstream.

**Comment by al-lac** [comment]
Ok, found a potential solution, see #1983

**Comment by nmfretz** [comment]
> Ok, found a potential solution, see https://github.com/getumbrel/umbrel-apps/pull/1983

Excellent, great catch @al-lac! I will take a look at https://github.com/getumbrel/umbrel-apps/pull/1983

**Pull request closed without merging**
