### PR TITLE
Update homebridge to version 1.8.4-2024-10-25

### PR DESCRIPTION
**Pull request by nmfretz**
🤖 This is an automated pull request to update homebridge to version 1.8.4-2024-10-25. This PR must be reviewed and tested before merging.

### CODE REVIEW

**Comment by nmfretz** [comment]
🤖 This is an automated summary of installation tests for homebridge:

- ✅ App successfully installed in umbrel-dev instance
- ✅ App successfully listed in umbrel.yaml
- ✅ App UI successfully returns a 200 status code
- 📸 Screenshot of the app:
  App Screenshot

**This PR must still be reviewed and tested before merging.**

**Comment by nmfretz** [comment]
Reviewed and tested (fresh install and app update)

**Comment by zavan** [comment]
Can we get v1.9.0?

Thanks!

**Comment by al-lac** [comment]
@zavan done via #2434

**Pull request merged**
