### PR TITLE
immich update v1.73.0

### PR DESCRIPTION
**Pull request by swarupbhc**
v1.73.0

Please make sure the mobile app and the server are on the same version to see the album displayed on the mobile app.

Welcome to release v1.73.0 of Immich. There are many improvements in this version that you will like. Some of the key highlights include:

- Optimized viewing experience for the Album page.
- Added option to configure the generated thumbnail resolution.
- Added option to toggle visibility of the memory reel.
- Better quality for thumbnails and generated videos.

Change logs - https://github.com/immich-app/immich/releases/tag/v1.73.0

### CODE REVIEW

**Comment by swarupbhc** [comment]
Hi @nmfretz can you please review and merge this update request?

**Comment by ankit5902** [comment]
Hello, @swarupbhc, appreciate your efforts in creating the pull request. I have some suggestions for modifications considering that Immich has transitioned to using images via GitHub Container Registry (ghcr.io). Could you kindly make the following changes to the images:

1. `server` & `microservices`: ghcr.io/immich-app/immich-server:v1.73.0@sha256:9ffecf7b8e1d65de4a82e1c47a5d1297a353703b4f511dc4b08fbb2a822da576

2. `machine-learning`: ghcr.io/immich-app/immich-machine-learning:v1.73.0@sha256:ce503c3049db762dbbb2edefaf2c3dbb059f1c4f59aa1ccd470b418fec48f880

3. `web`: ghcr.io/immich-app/immich-web:v1.73.0@sha256:825ac5d717f8a677b314c16df6d4cdc69b42b76f1e46d905f60619537d0becfe

4. `proxy`: ghcr.io/immich-app/immich-proxy:v1.73.0@sha256:34fa5707abf029d392a77515cfb27fd78c4d3fd59816b770e06a2be1b3180487

5. `typesense`, `redis` and `postgres` remain unchanged.


Also, I noticed that you used the SHA-256 of linux/amd64 in referencing the image. While this might/might not have a significant impact, it is a best practice to use the version-specific SHA-256 checksum for image referencing, unless the image is just for a specific architecture.

**Comment by nmfretz** [comment]
Thanks for keeping on top of this @swarupbhc.

And thanks @ankit5902 for the excellent review and suggested changes! It is a massive help and I really appreciate it. I double checked the image digests and can confirm they are correct.

> Also, I noticed that you used the SHA-256 of linux/amd64 in referencing the image. While this might/might not have a significant impact, it is a best practice to use the version-specific SHA-256 checksum for image referencing, unless the image is just for a specific architecture.

Great catch. And actually, for Umbrel's use-case this matters a lot because Umbrel can be run on x86 architectures (amd64), as well as on a Raspberry Pi (arm64 architecture). If only the amd64 digest is provided, then Raspberry Pi users would install a broken app. They would see an exec format error in any non-arm64 containers. Something like:
`exec /init: exec format error`

**Comment by ankit5902** [comment]
@nmfretz, thank you for your insights and for pointing out the implications for users on different architectures. It's indeed important to provide the correct image references to maintain the app's compatibility across various platforms.

**Comment by swarupbhc** [comment]
Hi @ankit5902 thanks a lot for the suggestion, I'm beginner to docker eco-system. @nmfretz I've made the changes, please review and proceed further

**Comment by nmfretz** [comment]
Excellent, thanks again for keeping us up-to-date on Immich @swarupbhc! Really appreciate you doing this.

I have tested  on arm64 and x86(amd64). Going live to the app store 📸

---------------------------------------------
If you're curious on how to find the correct multi-arch Docker image digests for future updates:

You can see on Immich's [ghcr.io](https://github.com/orgs/immich-app/packages?repo_name=immich) or [dockerhub](https://hub.docker.com/r/altran1502/immich-server/tags) that the tagged images are available for both arm64 and amd64:

ghcr.io
image

dockerhub
image

The above screenshots mean that a multi-arch image is available for v1.73.0 that will work for amd64 and arm64 architectures. To get the actual digest for the multi-arch image (the one that will result in both arm64 and amd64 users downloading a compatible image), you can run the following command: 

`docker pull <image>:<tag>`

So, for v1.73.0 you would run:
- for ghcr.io --> `docker pull ghcr.io/immich-app/immich-server:v1.73.0`
- for dockerhub --> `docker pull altran1502/immich-server:v1.73.0`

The multi-arch digest will be output to your console:
In this case it is `sha256:9ffecf7b8e1d65de4a82e1c47a5d1297a353703b4f511dc4b08fbb2a822da576`
```
$ sudo docker pull ghcr.io/immich-app/immich-server:v1.73.0
v1.73.0: Pulling from immich-app/immich-server
Digest: sha256:9ffecf7b8e1d65de4a82e1c47a5d1297a353703b4f511dc4b08fbb2a822da576
Status: Image is up to date for ghcr.io/immich-app/immich-server:v1.73.0
ghcr.io/immich-app/immich-server:v1.73.0
```

Also, one nice thing about the ghcr.io UI, compared to dockerhub, is that when an image is multi-arch you can actually see the multi-arch digest here: 
image

**Comment by swarupbhc** [comment]
@ankit5902 @nmfretz there is something wrong, I'm unable to install latest immich app on my raspberry pi.

**Comment by nmfretz** [comment]
@swarupbhc I just tested on my raspberry pi again and I'm able to successfully install the app.

Do you by chance have an old version of your forked repo checked out for testing on your raspberry pi? If so, it may be pulling the amd64 images instead of the arm64 ones.

**Comment by swarupbhc** [comment]
@nmfretz No there is no forked repo on my device, It's stuck on "installing" state, tried 3/4 times, maybe tomorrow I'll try to reinstalling the whole umbrel os.

**Comment by swarupbhc** [comment]
@nmfretz thanks, I tried again and it's installed successfully, maybe there was some server side issue from github/docker.

**Comment by nmfretz** [comment]
excellent, glad to hear! If you're curious and want to figure out what happened you can ssh into your pi and look at the karen logs which will give you details on the immich install

1. `ssh umbrel@umbrel.local`

2. `tail -n 250 ~/umbrel/logs/karen.log`

**Pull request merged**
