### PR TITLE
Update Snort v0.1.11

### PR DESCRIPTION
**Pull request by v0l**

### CODE REVIEW

**Comment by nmfretz** [comment]
Sorry for the delay @v0l.  It looks like `git.v0l.io/kieran/snort:v0.1.10` is only built for arm64, unlike previous tags that were multi-arch and so would work for both arm and x86 Umbrel users. Please ping me when the multi-arch image is up and I'll get on this right away to not delay you any further.

**Comment by nmfretz** [comment]
@v0l pinging again in case you missed this.

**Comment by v0l** [comment]
Hey, yea sorry forgot to come back to this, i guess Gitea doesn't support multi-arch builds because i certainly am building them, will push images to docker hub instead

**Comment by nmfretz** [comment]
> i guess Gitea doesn't support multi-arch builds because i certainly am building them, will push images to docker hub instead

Damn that's too bad about Gitea. Thanks for pushing to docker hub. I changed the digest to the multi-arch one and tested on amd64 and x86. Working great!

**Pull request merged**
