### PR TITLE
Update LndBoss to 2.17.3

### PR DESCRIPTION
**Pull request by niteshbalusu11**
Signed-off-by: Nitesh Balusu <niteshbalusu@icloud.com>

- Fixed a bug where old config is being used for auto fees updates.

https://github.com/niteshbalusu11/lndboss/blob/master/CHANGELOG.md

### CODE REVIEW

**Comment by niteshbalusu11** [comment]
Sorry found a stupid bug that needed fixing so had to open another PR in a short interval.

**Comment by nmfretz** [comment]
No problem at all @niteshbalusu11! I'll test this out tomorrow. And thanks for cleaning up some of the old version release notes. Much appreciated.

**Comment by nmfretz** [comment]
Thanks for this update @niteshbalusu11. I have tested on both arm64 and amd64 with no issues.

Merging now.

**Comment by nmfretz** [comment]
Also, this is a great GUI you've made for balance of satoshis @niteshbalusu11! I have added it to my arsenal of LND tools.

**Pull request merged**
