### PR TITLE
App Submission: Passky Client

### PR DESCRIPTION
**Pull request by zigazajc007**
# App Submission

### App name
Passky Client

### 256x256 SVG icon
_(Submit an icon with no rounded corners as it will be dynamically rounded with CSS. GitHub doesn't allow uploading SVGs directly, so please upload your icon to an alternate service, like https://svgur.com, and paste the link below.)_

https://svgshare.com/i/eSC.svg

### Gallery images
_(Upload 3 to 5 high-quality gallery images (1440x900px) of your app in PNG format, or just upload 3 to 5 screenshots of your app and we'll help you design the gallery images.)_

Screenshot

Screenshot2

Screenshot3

Screenshot4

Screenshot5

### I have tested my app on:
- [ ] [Umbrel dev environment](https://github.com/getumbrel/umbrel-dev)
- [ ] [Umbrel OS on a Raspberry Pi 4](https://github.com/getumbrel/umbrel-os)
- [x] [Custom Umbrel install on Linux](https://github.com/getumbrel/umbrel#-installation)

### CODE REVIEW

**Comment by zigazajc007** [comment]
The Passky Client version 8.1.0 has undergone an update and is now built on the nginx:alpine image, resulting in a more compact size.

**Review by nevets963 — COMMENTED** [review]
@zigazajc007 I may have a hit a bug, as I can't seem to store a password under a user account I just created. I am getting this error modal:

Screenshot 2023-02-03 at 00 00 44

Any ideas?

**Comment by zigazajc007** [comment]
> @zigazajc007 I may have a hit a bug, as I can't seem to store a password under a user account I just created. I am getting this error modal:
> 
> Screenshot 2023-02-03 at 00 00 44
> 
> Any ideas?

This can happen if your token for authentication expires on the server or it has been changed by the client.

So if you have restarted Passky Server all tokens from the cache will be deleted and all users will need to re-login.
Passky Server will store the token in the cache for up to an hour (The maximum session duration that can be set in the client).
This can also happen if you have deleted your Passky account with Admin Panel while you have been still logged in.

Does everything work normal if you re-log?

**Comment by nevets963** [comment]
@zigazajc007 Ok, looks like it's working now. I must have screwed something up during testing.

**Review by nevets963 — APPROVED** [review]

**Comment by nevets963** [comment]
@zigazajc007 It looks like we previously merged into the graphics for the Passky Client before (several months ago) - but we did just push a 5th image. They're located here: https://github.com/getumbrel/umbrel-apps-gallery/tree/master/passky-client Let me know if you're still happy those set of images, and if so, we can merge this in.

**Comment by zigazajc007** [comment]
> @zigazajc007 It looks like we previously merged into the graphics for the Passky Client before (several months ago) - but we did just push a 5th image. They're located here: https://github.com/getumbrel/umbrel-apps-gallery/tree/master/passky-client Let me know if you're still happy those set of images, and if so, we can merge this in.

Images are quite outdated, but this shouldn't be a problem. You can marge it.

**Comment by nevets963** [comment]
Merged 🚀 It feels great to see another high quality app in the Umbrel App Store. Keep up the great work on Passky!

**Pull request merged**
