### PR TITLE
update Immich to v1.107.2

### PR DESCRIPTION
**Pull request by mirceavesa**

### CODE REVIEW

**Comment by joaovictor-local** [comment]
:heavy_check_mark:  Tested on my umbrelOS 1.2.1

**Comment by nmfretz** [comment]
Wonderful, thanks for this update @mirceavesa. Great work on your first PR here!

I've changed the release notes so that they are the [1.107.0 ones](https://github.com/immich-app/immich/releases/tag/v1.107.0). These will be the most relevant for umbrelOS users because we are still pre-1.107.0 in this app store, 1.107.0 has the major changes, and the point releases afterwards are for the mobile app and hotfixes so they wouldn't mean much to users reading the notes.

image

Tested and going live.

**Comment by nmfretz** [comment]
And thank you for testing @joaovictor-local 🙏

**Comment by mirceavesa** [comment]
Thank you very much for clarifying, @nmfretz ! :) Understood and will pay attention to this on the future updates! :)

**Comment by nmfretz** [comment]
Thanks @mirceavesa. Absolutely no worries at all about the release notes though. That is only a personal preference on my end.

**Pull request merged**
