### PR TITLE
Update Krystal Bull images to include autologin

### PR DESCRIPTION
**Pull request by Christewart**
Updates Krystal Bull docker images to include autologin functionality

The backend image:
https://hub.docker.com/layers/249479785/bitcoinscala/bitcoin-s-oracle-server/1.9.2-42-83cff9a4-SNAPSHOT/images/sha256-ca622219d3502f6970ae920b3c26ed05011de867d51fdb864d9df32914a2bbc1?context=repo

the frontend image: 
https://hub.docker.com/layers/249503207/bitcoinscala/oracle-server-ui/1.9.2-f44ad4a4-SNAPSHOT/images/sha256-1338a36213803e98330d844b4ef877d7e56a149394a985f76f29ff25d016fb04?context=repo

### CODE REVIEW

**Comment by nevets963** [comment]
@Christewart Is this good for a review too? I still a reference to `$APP_PASSWORD`.

**Comment by Christewart** [comment]
> @Christewart Is this good for a review too? I still a reference to `$APP_PASSWORD`.

fixed

**Comment by nevets963** [comment]
@Christewart Could you also update the manifest with the desired version otherwise I have to somewhat guess this and ideally you should set/control this, so that if users have a problem they can quote a version you have set. Thanks!

**Comment by nevets963** [comment]
@Christewart Awesome, I will test this in the morning!

**Comment by lukechilds** [comment]
@Christewart just pining here too to double check that these image snapshots are still the ones you want to ship and see if you wanna add a `releaseNotes` property to `umbrel-app.yml`.

**Comment by lukechilds** [comment]
@rorp @user411 @Christewart just a friendly ping on this incase you missed it.

**Comment by Christewart** [comment]
Added the release notes property, this should be good to go.

**Review by lukechilds — APPROVED** [review]
Tested and working great!

**Pull request merged**
