### PR TITLE
Update PeerSwap to v1.6.3

### PR DESCRIPTION
**Pull request by Impa10r**
Simplifies New Swap interface, adds BTC send with coin select, bug fixes. 

See full changelog here: https://github.com/Impa10r/peerswap-web/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by Impa10r** [comment]
Please don't approve yet, there was a bug report...

**Comment by nmfretz** [comment]
Thanks @Impa10r! Do you have any release notes you'd like to add?

**Comment by Impa10r** [comment]
> Thanks @Impa10r! Do you have any release notes you'd like to add?

Hi, are the notes in umbrel-app.yml not sufficient?

**Comment by nmfretz** [comment]
Whoops, sorry about that @Impa10r, they look fine. I had been comparing https://github.com/getumbrel/umbrel-apps/pull/1190/commits/e0d60bf8e2b96097660f7d305cfdb635e6f74da3 and didn't realize there were many version changes prior.

Going live!

**Pull request merged**
