### PR TITLE
Update Urbit to v1.15.0

### PR DESCRIPTION
**Pull request by mopfel-winrux**
Update to use the official urbit bianries. This will allow users to autoupdate

### CODE REVIEW

**Review by nevets963 — COMMENTED** [review]
@mopfel-winrux Thanks for the app update!

On looking closer, we can't accept an app that has auto-update functionality like what is described in the feature notes because it would circumvent our review process to check that the app is functional on both `arm64` and `amd64`, and perhaps more importantly, if the location of the binary (on the Internet) gets hacked, it means a compromised update could get rolled out without users knowing.

**Comment by mopfel-winrux** [comment]
the autoupdate functionality was approved for `amd64` prior to this, and the pulling of the binary has been the core functionality for both `amd64` and arm64. Do I need to submit a PR request every time the urbit binary is updated?"

**Comment by nevets963** [comment]
Yes. For each new version that you wish to roll out, we require a PR which would contain up to date Docker images for functionality that you wish to release.

**Comment by mopfel-winrux** [comment]
I modified this to not autoupdate

**Review by nevets963 — APPROVED** [review]
@mopfel-winrux Thanks for reverting to versioned Docker images for Urbit updates.

I just patched up the `docker-compose.yml` file and added some release notes.

Tested on`arm64` and `amd64`.

This is approved from me. If you're happy with my changes, then I'll merge this in 🚀

**Comment by mopfel-winrux** [comment]
looks good to me

**Pull request merged**
