### PR TITLE
Update Mattermost to v10.3.1

### PR DESCRIPTION
**Pull request by al-lac**
Tested update and install on Raspberry Pi 5 and Umbrel Home.

### CODE REVIEW

**Comment by nmfretz** [comment]
Excellent. Thanks for this @al-lac. Tested and working great.

image

Shall I add Mattermost to the list of apps that our auto-update script will update? Or would you rather keep doing them manually?

**Comment by al-lac** [comment]
Great, thanks for testing as well! :-) 

Feel free to add it to the auto-update script. Is the script / action also open source? Would be really interesting to see how you automatically deploy and screenshot an app.

**Comment by nmfretz** [comment]
> Feel free to add it to the auto-update script. 

Great, I've added it!

> Is the script / action also open source? Would be really interesting to see how you automatically deploy and screenshot an app.

Ah, it's just code I have locally on my computer at the moment. It's in a bit of a hacky state as I tweak/modify it to get it to be even more automated. I haven't touched it in quite a long time, so will need to improve and clean things up.

But at a high level this is what it does:

- Checks for a new version of the app by fetching latest version from GitHub and comparing against current version in the umbrel-app.yml. I've got some logic to deal with tags and versions... for example, we want to grab the `latest` version if available and not use a `pre-release`. Also fetches release notes.

- Uses AI to analyze the release notes and compose files and identify which Docker images need updating.

- Checks that the identified images we're updating to support both linux/amd64 and linux/arm64 architectures (I'm using `mplatform/mquery` as a super easy way to do this) and fetches the verified digests.

- Uses AI to update the docker-compose.yml and umbrel-app.yml files. This is the trickiest part and relies on good prompting. You'll see by the completed updates in this repo that I now usually don't need to make edits, but occasionally do when it can't grab the right image for some reason or it adds some irrelevant release note point, etc.

- Creates a new local branch, commits changes, creates a remote PR.

- Installs the app in an `umbrel-dev` instance, verifies that the app was installed, tests the UI accessibility, and then uses a headless browser to take a screenshot of the UI. Then it adds these testing results to the PR.

Overall, this allows me to focus on testing and checking the release notes for breaking changes instead of getting bogged down in manually making the update. The auto-tester gives me the "fresh install" test that I can quickly verify because it will be freshly installed in my umbrel-dev instance. And then I can focus on testing that an app update persists data, etc.

I haven't updated this table in a bit, but here's a rough look at how many apps the updater-script is "responsible" for:

```
 * Update Process for Maintained Apps (141 total):
 * +------------------------------------------------+-------+-------+
 * | Update Method                                  | Count |     % |
 * +------------------------------------------------+-------+-------+
 * | Maintained by app developer                    |    35 |  25%  |
 * | Updateable via script without manual input     |    76 |  54%  |
 * | Updateable via script with manual input        |    22 |  16%  |
 * | Maintained by Umbrel (development work needed) |     8 |   6%  |
 * +------------------------------------------------+-------+-------+
 *
 ```
 
 For the update script to work without intervention the app's github repo must have (1) tags and (2) release notes. If they don't have both of these then they fall under the `Updateable via script with manual input` category where I pass in version and raw release notes via the command line when running the update script.

**Comment by al-lac** [comment]
Wow, really nice workflow! 🚀 

I thought that those release notes maybe are refined by AI 😁 

I guess with some effort most of it could be done via GitHub Actions, so it is not dependent on a local machine. But not sure how the umbrel-dev tests and so on would work there.

**Pull request merged**
