### PR TITLE
Update nextcloud to version v30.0.0

### PR DESCRIPTION
**Pull request by nmfretz**
🤖 This is an automated pull request to update nextcloud to version v30.0.0. This PR must be reviewed and tested before merging.

### CODE REVIEW

**Comment by nmfretz** [comment]
🤖 This is an automated summary of installation tests for nextcloud:

- ✅ App successfully installed in umbrel-dev VM
- ✅ App successfully listed in umbrel.yaml
- ✅ App UI successfully returns a 200 status code
- 📸 Screenshot of the app:
  App Screenshot

**This PR must still be reviewed and tested before merging.**

**Comment by nmfretz** [comment]
This will require a rewrite of the pre-start script to properly handle migrations now that we are on v30

**Comment by dennysubke** [comment]
Thanks for the update!

However, I receive a warning in my Nextcloud instance about the MariaDB version in use:

“For optimal performance and stability, it is recommended to use MariaDB version > 10.6 or 11.4.”
cb1295ad0e4c1ed99cddfeb7a0ff1561b1f14345

**Comment by nmfretz** [comment]
Thanks for noting this @dennysubke! Shall we schedule the mariadb update for Nextcloud 30.0.1 which should be out soon (https://github.com/nextcloud/server/milestone/279)?

We'll need to be careful when updating mariadb and may need to run some mariadb specific migration logic in the pre-start script when we do so.

**Comment by dennysubke** [comment]
Thanks for the heads-up @nmfretz ! Scheduling the MariaDB update around the release of Nextcloud 30.0.1 sounds like a good plan.

**Comment by ant0nwax** [comment]
Hi, I just upgrade to Nextcloud 30.0.1 and I understand that the MariaDB upgrade from 10.3 to next useful version will be  in 30.0.2 earliest and is NOT needed to be done manually.

Further I vote +1 for [Maps Nextcloud App](https://github.com/nextcloud/maps) to be compatible to NC 30.

After updating I could click "Allow Untested App" and clicked "Enable".
Why is it actually not compatible? Does anyone know? Maybe it is just false information. 
Testing it 1 minute seems to work.

**Comment by dennysubke** [comment]
> Hi, I just upgrade to Nextcloud 30.0.1 and I understand that the MariaDB upgrade from 10.3 to next useful version will be in 30.0.2 earliest and is NOT needed to be done manually.
> 
> Further I vote +1 for [Maps Nextcloud App](https://github.com/nextcloud/maps) to be compatible to NC 30.
> 
> After updating I could click "Allow Untested App" and clicked "Enable". Why is it actually not compatible? Does anyone know? Maybe it is just false information. Testing it 1 minute seems to work.

The compatibility issues with apps can sometimes be due to version constraints set by the app developers. They might mark an app as incompatible with a new version of Nextcloud until they have fully tested it. In some cases, the app might work just fine, but the developers want to avoid potential issues for users who rely on it.

**Comment by dennysubke** [comment]
@nmfretz  The time has come, v30.0.1 is available: https://hub.docker.com/layers/library/nextcloud/30.0.1-apache/images/sha256-a4e0f2c053010cc391fd63040779553ff2a266ea52c1e37555f0a967eb466ec3?context=explore

**Pull request merged**
