### PR TITLE
App Submission: N8N

### PR DESCRIPTION
**Pull request by IMPranshu**
# App Submission

### N8N
...

### 256x256 SVG icon
https://github.com/IMPranshu/svg-logo/blob/main/n8n.svg
...

### Gallery images
Screenshot from 2022-11-16 01-29-03
Screenshot from 2022-11-16 01-29-17
Screenshot from 2022-11-16 01-29-29
Screenshot from 2022-11-16 01-29-52
Screenshot from 2022-11-16 01-30-23

...

### I have tested my app on:
- [ ] [Umbrel dev environment](https://github.com/getumbrel/umbrel-dev)
- [x] [Umbrel OS on a Raspberry Pi 4](https://github.com/getumbrel/umbrel-os)
- [x] [Custom Umbrel install on Linux](https://github.com/getumbrel/umbrel#-installation)

### CODE REVIEW

**Comment by matbrgz** [comment]
Why this want merged yet? I'm looking for this ASAP.

**Review by nevets963 — APPROVED** [review]
@IMPranshu Thanks for also submitting n8n! I've just deployed a workflow that will come in handy!

Tested on `arm64` and `amd64`. Approved from me.

@mayankchhabra Could you help us prepare gallery assets for n8n?

Once gallery assets have been merged in, I'll do 1 final test and then merge this in 🚀

**Comment by nevets963** [comment]
Gallery assets are located here: https://github.com/getumbrel/umbrel-apps-gallery/pull/24 Will start on final tests today before merging.

**Comment by nevets963** [comment]
Another great addition to the app store, thank you @IMPranshu ! Merging now! 🚀

**Comment by itsdoublearon** [comment]
Can somebody please update this for umbrel. Several versions behind at the moment and there are a few security patches.

**Pull request merged**
