### PR TITLE
Update Helipad to v0.1.10.5

### PR DESCRIPTION
**Pull request by ericpp**
Updates the Helipad app to the latest Docker version and includes release notes with changes since the last version.

### CODE REVIEW

**Review by ParthJadhav — APPROVED** [review]
- Multi-Platform Image ✅ 
- Release notes ✅ 
- Working update ✅ 

Thanks for the contribution @ericpp !!

**Comment by nmfretz** [comment]
Excellent, thanks for keeping Helipad up to date on Umbrel @ericpp, we really appreciate it!

I noticed that the Docker image isn't tagged with a version, and hasn't been since 0.1.10:
`podcastindexorg/podcasting20-helipad@sha256:6767de3126b0a7d317f7c87766a1f063baa44fb85dc5496c794ff9aff306a4c1`

When I check out the UI, it still shows the version as 0.1.10 instead of 0.1.10.5. Do you happen to know if there are any plans to continue version tags?

image

**Comment by nmfretz** [comment]
ah, I see this issue and related PR that you are involved with. Excellent.
https://github.com/Podcastindex-org/helipad/issues/56
https://github.com/Podcastindex-org/helipad/pull/64

This is good to go as-is and we can handle adding back in a version-tagged image for the next update. The sha256 digest you included locks us in anyways.

**Comment by ericpp** [comment]
Thanks for merging! The current version is still `0.1.10` but there have been several updates since that version was pushed out. I added `.5` to the version to indicate those updates. I need to work with the upstream owner to have him push out a new official version number.

**Pull request merged**
