### PR TITLE
App submission: Seafile

### PR DESCRIPTION
**Pull request by swarupbhc**
Seafile is an open source cloud storage system with privacy protection and teamwork features. Collections of files are called libraries. Each library can be synced separately. A library can also be encrypted with a user chosen password. Seafile also allows users to create groups and easily sharing files into groups.

## Feature Summary

Seafile has the following features:

### File syncing

1. Selective sync for any folder.
2. Correctly handles file conflicts based on history instead of timestamp.
3. Only transfer content delta to the server. Interrupted transfers can be resumed.
4. Sync with two or more servers.
5. Sync with existing folders.

### File sharing and collaboration

1. Sharing folders between users or into groups.
3. Download links with password protection
4. Upload links
5. Version control

### Drive client

* Access all files in the cloud via virtual drive.
* Files are synced on demand.

### Privacy protection

1. Library encryption with a user chosen password.
2. Client side encryption when using the desktop syncing.

### Online documents and knowledge management (New)

* Online Markdown editing in WYSIWYG way
* A draft review workflow for online documents
* Metadata management, including
  * File labels
  * Related documents
* Wiki mode
* Realtime notifications

## Source repositories for Seafile components

Each component of Seafile has its own source code repository on Github.

* Sync client daemon (this repository): https://github.com/haiwen/seafile
* Sync client GUI: https://github.com/haiwen/seafile-client
* Server core: https://github.com/haiwen/seafile-server
* Server web UI: https://github.com/haiwen/seahub
* iOS app: https://github.com/haiwen/seafile-iOS
* Android app: https://github.com/haiwen/seadroid
* WebDAV: https://github.com/haiwen/seafdav

### CODE REVIEW

**Comment by swarupbhc** [comment]
Hi @nmfretz can you please review this submission?

**Comment by swarupbhc** [comment]
@nmfretz still waiting for the review

**Comment by swarupbhc** [comment]
@ankit5902  can you please help me with this?

**Comment by nmfretz** [comment]
Thanks for proactively pushing us forward with Seafile @swarupbhc! Since @IMPranshu put in hard work to bring Seafile to Umbrel with [this open PR](https://github.com/getumbrel/umbrel-apps/pull/676), let's give him another week to respond there. I will keep both PR's open for now.

**Comment by nmfretz** [comment]
Closing this in favour of https://github.com/getumbrel/umbrel-apps/pull/676. Thanks for pinging me in that PR @swarupbhc.

**Pull request closed without merging**
