### PR TITLE
LightningNetwork+ minor updates to v.0.1.30

### PR DESCRIPTION
**Pull request by lnplus**
- Updated wording in navigation
- Updated intro pages
- Updated about page
- Added improved footer
- Improved error handling

### CODE REVIEW

**Comment by nmfretz** [comment]
Thanks for this @lnplus! I have tested on amd64 and arm64 and all works well. 

Can you please push a change to remove the `.vscode` directory from this PR? Once that is done, this is good to go live ⚡️

**Comment by lnplus** [comment]
@nmfretz Thank you for your work. I did as requested.

**Comment by nmfretz** [comment]
I'll give 0.1.31 a test!

**I still see the `.vs-code` directory/files in the PR though.** Could you please try pushing another commit with it removed?

image

**Comment by lnplus** [comment]
Apologies! I removed it from the app previously, but not this repo. 😬 Removed it from this too.

**Comment by nmfretz** [comment]
No problem! Tested again on amd64 and arm64. Going live ⚡️

**Pull request merged**
