### PR TITLE
App Submission: LibreOffice

### PR DESCRIPTION
**Pull request by IMPranshu**
# App Submission

### LibreOffice
...

### 256x256 SVG icon
https://svgshare.com/i/nav.svg
...

### Gallery images
libre4
libre3
libre2
libre1

...

### I have tested my app on:
- [ ] [Umbrel dev environment](https://github.com/getumbrel/umbrel-dev)
- [x] [Umbrel OS on a Raspberry Pi 4](https://github.com/getumbrel/umbrel-os)
- [x] [Custom Umbrel install on Linux](https://github.com/getumbrel/umbrel#-installation)

### CODE REVIEW

**Review by nevets963 — APPROVED** [review]
@IMPranshu Thanks for submitting the PR to add LibreOffice to the App Store! It's pretty impressive how this all works and even smoothly on a tiny Raspberry Pi!

Tested on `arm64` and `amd64`.

Approved from me 🚀 

@mayankchhabra Please could you work on the graphics to complete this PR?

**Comment by IMPranshu** [comment]
Thanks for fixing the PR @nevets963. Yes, I was also skeptical if this will even work but it worked like a breeze. Felt glad when it worked. Can't wait to hear the user's reaction after using it :+1: .

**Comment by nevets963** [comment]
The App Store assets have been pushed here: https://github.com/getumbrel/umbrel-apps-gallery/pull/18

I will do a final test, then if good, merge 🚀

**Comment by IMPranshu** [comment]
Thanks, @nevets963.

**Pull request merged**
