### PR TITLE
lightning-terminal: update to v0.9.2-alpha

### PR DESCRIPTION
**Pull request by ellemouton**
Hi there! Here to bump Litd to v0.9.2-alpha. 

See the release notes here: https://github.com/lightninglabs/lightning-terminal/releases/tag/v0.9.2-alpha

Thanks!

### CODE REVIEW

**Comment by nmfretz** [comment]
Thanks for this @ellemouton. Looks like the Lightning Node app will need to be bumped to [v0.16.0-beta](https://hub.docker.com/layers/lightninglabs/lnd/v0.16.0-beta/images/sha256-92a13988d42bb5be70a3896c789bb693732de801509db76b3507b68d65537c16?context=explore), or else lightning-terminal will break on update. I'll look into this and then come back to your PR.

> Please take special note of the Breaking API changes.

Thanks for this note. Looks like we should be okay because we are running in "remote" mode instead of "integrated" mode. I will confirm during testing.

**Comment by nmfretz** [comment]
@ellemouton. Lightning Node app update is almost ready. I will push your update soon.

**Comment by ellemouton** [comment]
hi @nmfretz ! I have pushed a new commit since Litd v0.9.1-alpha was just released

**Comment by ellemouton** [comment]
now updated with v0.9.2-alpha :)

**Comment by nmfretz** [comment]
Thanks again @ellemouton! Tested on amd64 and arm64 and all looks good. I made a very small tweak to the whitespace in the release notes.

Going live ⚡️

**Pull request merged**
