### PR TITLE
App Submission: Linkwarden

### LINKED ISSUE #1643: [App Request] Linkwarden
https://github.com/linkwarden/linkwarden

### PR DESCRIPTION
**Pull request by al-lac**
# App Submission

### App name
Linkwarden
Fixes #1643

### 256x256 SVG icon

Could not find an official svg, converted the official png that can be found here as best as I could:
https://docs.linkwarden.app/img/logo.png

https://svgur.com seems to be offline, uploaded it here for now:
https://filetransfer.io/data-package/RY5qNfVd#link

### Gallery images
https://github.com/linkwarden/linkwarden/blob/main/assets/dashboard.png
https://docs.linkwarden.app/assets/images/showcase_image-2c911c624807d666e2d4feae7879d798.png
https://docs.linkwarden.app/assets/images/single_collection-ae357cb585f175e779783437fbdf0e0f.png

### I have tested my app on:
- [x] umbrelOS on a Raspberry Pi
- [ ] umbrelOS on an Umbrel Home
- [x] umbrelOS on Linux VM

### CODE REVIEW

**Comment by nmfretz** [comment]
Thanks for your latest submission here @al-lac! I'm just catching up on some tasks and will get to this later in the week.

**Comment by nmfretz** [comment]
An absolutely perfect submission @al-lac 🤯 I have literally nothing to add.

We'll get gallery assets made up and get this to the app store!

**Comment by nmfretz** [comment]
oh sorry, you dropped this 👑

**Comment by nmfretz** [comment]
Sorry for the delay on this @al-lac. Gallery assets are ready to go. Going live! Thanks again for the wonderful submission. 

image

**Comment by al-lac** [comment]
Looks amazing! 🤩 

And perfect timing as I got my Umbrel Home today 🚀

**Comment by nmfretz** [comment]
Excellent! I hope the setup goes smoothly! Whatever you do, don't open Settings > Device Info > and then click 3 times on the umbrel home image 😉

**Comment by al-lac** [comment]
Oh wow, I for sure did not click 3 times on it ⚡ 

Yes everything went really smoothly! 
I am not sure if i broke anything though by changing the hostname to umbrel-home.local, did not want to use umbrel-2 as i already have my raspberry in the same network 😁

**Comment by Tharkis** [comment]
So, I have linkwarden installed and it appears to be working fine. However, I wanted to make use of the new AI tagging feature. AI tagging requires a couple of parameters to be changed in the .env file in addition to installing Ollama. 

I've got Ollama installed, but I need to update the .env file to include the following lines: 

`NEXT_PUBLIC_OLLAMA_ENDPOINT_URL=http://localhost:11434
OLLAMA_MODEL=phi3:mini-4k`

What's the best way to go about doing this? I want to avoid breaking the changes in any future updates.

**Comment by Niclassslua** [comment]
image

<br><br>

Compared to other App Icons the Linkwarden icon is very low quality.

I would suggest using the one I uploaded. It's 900x900.

<br><br>

linkwarden

**Pull request merged**
