### PR TITLE
App Submission: Ghostfolio

### LINKED ISSUE #386: Add Ghostfolio to the Umbrel AppStore
It would be great to add the Ghostfolio App to the store. 

Ghostfolio is an open source wealth management software built with web technology. The application empowers busy people to keep track of stocks, ETFs or cryptocurrencies and make solid, data-driven investment decisions. The software is designed for personal use in continuous operation.

I am sure lot of users will benefit from it. As well, it already runs on Docker

### PR DESCRIPTION
**Pull request by BeauAgst**
# App Submission

Closes #386 

### App name
Ghostfolio

### 256x256 SVG icon
https://svgur.com/s/q3G

### Gallery images
I've not actually used the app myself, so @dtslvr may want to supply some better pictures to show it off!

ghostfolio-screenshot-5
ghostfolio-screenshot-4
ghostfolio-screenshot-3
ghostfolio-screenshot-2
ghostfolio-screenshot-1

### I have tested my app on:
- [ ] [Umbrel dev environment](https://github.com/getumbrel/umbrel-dev)
- [x] [Umbrel OS on a Raspberry Pi 4](https://github.com/getumbrel/umbrel-os)
- [ ] [Custom Umbrel install on Linux](https://github.com/getumbrel/umbrel#-installation)

@nevets963 have you thought about supporting markdown in the app store? I think it could really help with formatting and inserting links into content 👍🏼

### CODE REVIEW

**Review by nevets963 — APPROVED** [review]
@BeauAgst Many many thanks for submitting Ghostfolio into the Umbrel App Store! Overall, this was a super clean PR 😄 

I touched up a few tiny things - could you triple check those commits to make sure I haven't done anything silly?

Otherwise, I've tested this on `arm64` and `amd64` and it's working nicely.

This is approved from me. We only need to prepare the graphics now for the app store. I'll speak with our graphics designer and get this actioned.

**Comment by nevets963** [comment]
Graphics have been created and exist here: https://github.com/getumbrel/umbrel-apps-gallery/pull/37

**Comment by BeauAgst** [comment]
Hey @nevets963, the only thing I would question is that we've removed 3334 from the list of exposes ports, but the docker image only exposes 3333 by default. This port is already being used by another app from what I could tell

**Comment by nevets963** [comment]
@BeauAgst It looks like the server container is set to listen on port 3334 (https://github.com/getumbrel/umbrel-apps/pull/396/files#diff-f83aef0ad7dbb18e3a44a765cda67cedf674a3bcd528ed0d8ea9d8b1c6957656R15) which the App Proxy forwards onto (via the Docker bridge). The app is also set to use port 3334 (which is what the App Proxy opens on the host). ie. in 1 case the port 3334 is opened on the container, in the other, port 3334 is opened on the host so there aren't any conflicts.

**Comment by BeauAgst** [comment]
Amazing! I'm not much of a Docker expert, so thanks for explaining 🙏🏼

**Comment by nevets963** [comment]
Merged 🚀 

@BeauAgst Re Markdown support, currently we don't do this incase it introduces XSS as an attack vector - but I'm sure at some point we'll be able to do something to improve the formatting of app descriptions.

**Comment by dtslvr** [comment]
Thanks @BeauAgst for the _Ghostfolio_ app submission 👍🏻 
Is it already available in the _Umbrel_ app store? I would like to add the _Umbrel_ logo to the _Ghostfolio_ landing page.

**Comment by nevets963** [comment]
Yep 😄 It's already live in the App Store

Screenshot 2023-02-15 at 17 35 48

**Comment by dtslvr** [comment]
> Yep 😄 It's already live in the App Store

Thanks for the information @nevets963 😎

**Pull request merged**
