### PR TITLE
Update Thunderhub to v0.13.30

### PR DESCRIPTION
**Pull request by kilrau**
This updates ThunderHub from v0.13.29 to v0.13.30. Contains an important fix for Boltz Swaps.

### CODE REVIEW

**Comment by kilrau** [comment]
[nmfretz](https://github.com/nmfretz) (sorry for being pushy, but we are having support cases because of the Boltz claim fee bug this update fixes)

**Comment by kilrau** [comment]
@nmfretz Ssorry for being pushy, but we are having support cases because of the Boltz claim fee bug this update fixes.

**Comment by kilrau** [comment]
> @nmfretz Ssorry for being pushy, but we are having nasty support cases because of the Boltz claim fee bug this update fixes.

**Comment by nmfretz** [comment]
Very sorry for the delay @kilrau! Thanks for pinging me. I have tested on arm64 and x86 (amd64). Going live now.

FYI, if I'm unresponsive here please feel free to DM me on twitter or telegram especially if it is urgent.

**Pull request merged**
