### PR TITLE
[UPDATE] Btcpay server

### PR DESCRIPTION
**Pull request by highghlow**
Fix: #1049

Updated containers:
 - nicolasdoriev/nbxplorer:2.5.0 -> 2.5.2
 - btcpayserver/btcpayserver:1.12.5 -> 1.13.1
 - btcpaayserver:13.10 -> 13.13

I have partially tested the app on my Debian Umbrel, but because I don't have a bitcoin node (the synchronization takes Ages!) I can't fully verify that the app is working. It gets to starting the app, but because APP_LIGHTNING_NODE_DATA_DIR is null, it fails. The app should be working for people who have the lightning node. Test it on your machine. Just in case.

### CODE REVIEW

**Comment by Radiokot** [comment]
I'm running it without the Lightning node, just comment mounting APP_LIGHTNING_NODE_DATA_DIR in the `docker-compose` file

**Comment by highghlow** [comment]
> I'm running it without the Lightning node

Well, lightning is required for BTCPay. Even if the app itself supports running without lighnting, most people use it with lnd, so I'll keep that it.

**Comment by Radiokot** [comment]
Sure, I did not suggest commenting it in the `umbrel-apps` repo – just on your local machine, to test that it works.
You can use BTCPay without your own Lightning node and still use Lightning checkout, for example by connecting it to Alby in the store settings.

**Comment by nmfretz** [comment]
Thanks for this update @highghlow! Really appreciate all your work.

I have confirmed that there are no breaking changes, and have tested on arm64 and x86.
I also updated BTCPay's release notes to be a bit more user friendly since they are generally obscure and don't mean too much to the average user.

If you are ever interested in testing out the Bitcoin Node app you can install it, open the app, hit the 3 dots to get to Advanced Settings, change the network to `signet` and restart the node from within the Advanced Settings menu. This will download a 1GB blockchain on a test network. You could then install the Lightning Node and BTCPay server and they will also be on that test network.

**Pull request merged**
