### PR TITLE
Update the mempool app to v3.0.0

### PR DESCRIPTION
**Pull request by knorrium**
This PR enables integration testing with v3.0.0 of the mempool.space app.

One major new feature in this release is the ability to use the Mempool Accelerator™ from self-hosted nodes, including over Tor.

The feature is enabled by default and can be disabled by setting the `ACCELERATOR_BUTTON` variable to `false` on the frontend config.

Updated Docker documentation to come soon™.

Once the final image is published, I'll update the PR with the final hash, reduce the logging to `info` and squash all commits 🫡

### CODE REVIEW

**Comment by nmfretz** [comment]
Thanks @knorrium. Excited to test this out! Ping me when you are ready 🤝

> Once the final image is published, I'll update the PR with the final hash, reduce the logging to info and squash all commits

FYI, I will squash merge this when we're ready, so no need to squash your commits in your PR branch if you don't want.

**Comment by wiz** [comment]
> Excited to test this out! Ping me when you are ready 🤝

this build was prepared for your testing, please test it and give us your feedback

**Comment by knorrium** [comment]
@nmfretz I've been testing it on my Pi 4, Umbrel Home and Linux VM and found no issues so far, but it would be great if you could take a look as well.

We are very close to shipping 3.0.0 so this is almost final 🦾

**Comment by nmfretz** [comment]
Thanks @knorrium and @wiz. Really great work on this.

I have tested:
- both x86 and arm64 builds
- new accelerator functionality (works like a charm, including over tor)
- tested on mainnet and test networks (e.g., Bitcoin/Lightning/Electrs apps running on signet)
- app update and fresh install

-------------------------
Remaining Todos:
- [ ] umbrel to re-test once final images are available
- [ ] mempool to update release notes in `umbrel-app.yml` once available.

Out of curiosity, for this...
> The feature is enabled by default and can be disabled by setting the ACCELERATOR_BUTTON variable to false on the frontend config.

 are there plans to have configuration settings available within the UI for self-hosted instances in the future?

**Comment by nmfretz** [comment]
Also, we could consider adding a note in the umbrel-app.yml `releaseNotes` warning users that the app may take a while to fully come online after this major upgrade. As an upper bound for length of time, I tested on a super old 8GB RPi4 overloaded with apps and low on disk space, and it took about 10 minutes for the backend to fully come online.

```
$ sudo docker logs -f mempool_api_1
wait-for-it.sh: waiting 720 seconds for mariadb:3306
wait-for-it.sh: mariadb:3306 is available after 3 seconds
Aug  7 03:17:18 [146] NOTICE: <lightning> Starting Mempool Server... (15f1073)
.
.
.
.
Aug  7 03:26:54 [146] NOTICE: <lightning> The mempool is now in sync!
Aug  7 03:35:12 [146] INFO: <lightning> [Lightning] Starting Lightning Stats service
Aug  7 03:42:37 [146] INFO: <lightning> Starting lightning network forensics service
Aug  7 03:42:37 [146] INFO: <lightning> [Lightning] Caching funding txs for currently existing channels
Aug  7 03:43:08 [146] INFO: <lightning> [Lightning] Indexing channels funding tx 72313 of 73489 (98.39%) | elapsed: 31 seconds
Aug  7 03:43:38 [146] INFO: <lightning> [Lightning] Indexing channels funding tx 72884 of 73489 (99.17%) | elapsed: 61 seconds
Aug  7 03:43:50 [146] INFO: <lightning> [Lightning] Indexed 408 additional channels funding tx
```

**Comment by wiz** [comment]
Thanks for your testing, I'm glad to hear there were no issues. We are just waiting for a few translators to finish up and we will only merge string changes, so it should be nearly final.

On your RPI4, does it always take 10 minutes to sync the mempool or was that just after the upgrade? I would be curious to hear the startup time after upgrading, from a normal boot up.

As for a UI configuration panel, we feel this should be implemented on the Umbrel side similar to how you have UI to configure Bitcoin Core. For now the defaults are probably fine for everyone, and they can hack the docker environment variables if they want.

**Comment by nmfretz** [comment]
> On your RPI4, does it always take 10 minutes to sync the mempool or was that just after the upgrade? I would be curious to hear the startup time after upgrading, from a normal boot up.

Hey wiz, normal sync time (e.g., from restarting the v3.0 app) takes roughly half the time it does after an upgrade. My specific RPi4 test can be taken as a "reasonable" worst-case scenario for sync time, since this will mimic umbrelOS users with the lowest grade hardware who are running near their device's RAM and storage capacity limits.

Here are the sync times from my testing. These times are from `NOTICE: <lightning> Starting Mempool Server...` to `NOTICE: <lightning> The mempool is now in sync!`:

Pi 4 (microSD card + USB SSD)
- Update from 2.5 to 3.0: ~10 minutes
- 3.0 Restart: ~4 minutes

Pi 5 (NVMe)
- Update from 2.5 to 3.0: ~5 minutes
- 3.0 Restart: ~2 minutes

Umbrel Home and equivalent hardware would be even faster.

I have saved my backend logs from the above tests, so let me know if you want any other details (e.g., time take for specific services to start).

**Review by wiz — APPROVED** [review]
ACK
```
mempool/frontend:latest@sha256:ec84195e6d3050841efef99b9db2ec6f3b8cd64611df0c8dae026a41931ae58c
mempool/backend:latest@sha256:d48122e60e5f8fdd74874e23578ea606dbd3cd52bd2eeb2b68b56e69e54e3d82
```

**Comment by knorrium** [comment]
It's time.

**Comment by nmfretz** [comment]
Excellent, thanks @wiz and @knorrium. I have re-tested with the new images and we are good to go live. Really great work on 3.0.

We are just missing release notes, and I don't have access permissions to push changes to mempool's umbrel-apps fork. To avoid more back-and-forth I will merge this PR and add the following release notes in a separate commit:

```yaml
releaseNotes: >-
  The Mempool Open Source Project® v3.0.0 is here!


  This release features integration with our new Mempool Accelerator™ service to help you get your stuck Bitcoin transactions confirmed quickly.
  You can now submit accceleration requests directly to mempool.space from your own self-hosted instance of The Mempool Open Source Project®.
  

  Highlights:

    - Added Mempool Accelerator™ to accelerate TX from your own instance
    - Added Mempool Googles™ new mempool and blockchain analytics tool
    - Added RBF Timeline visualizations including support for FullRBF
    - Added CPFP and Effective Fee calculations in block visualizations
    - Added Liquid Network audit tool to verify holdings vs liabilities
    - Added new Wallet Balance widget for embedding into external sites
    - Added customizable CSS themes including a new high-contrast mode
    - Added optional support for FreecurrencyAPI fiat currencies
    - Added optional Redis support for faster in-memory database
    - Added support for legacy P2PK addresses and outputs
    - Added new block fees graph at /graphs/mining/block-fees
    - Added new fiat calculator at /tools/calculator
    - Re-implemented our GBT algorithm in rust for high performance
    - Re-designed transaction page with new mobile "pizza tracker" UI
    - Re-designed address page with new balance history over time
    - Improved Block Audit for accelerated transaction out-of-band fees
    - Improved Websocket API to support tracking multiple addresses
    - Improved search box now supports searching multiple networks
    - Improved TV View to add new circular clock face view

  Full release notes are found at https://github.com/mempool/mempool/releases
```

image

**Pull request merged**
