### PR TITLE
Updating Immich to 1.54.1

### PR DESCRIPTION
**Pull request by JimSB**
I've updated the image to v1.54.1 for 

- immich-server (it looks like the same immich-server tag is used under `server:` and `microservices:`)
- immich-machine-learning
- immich-web
- immich-proxy

I did not change redis:6.2-bullseye    _or_    postgres:14-bullseye

### CODE REVIEW

**Comment by nmfretz** [comment]
Thanks @JimSB! Of course they released version 1.55 like 4 hours after you opened this PR 🤦‍♂️. Looks like there are some [decent updates](https://github.com/immich-app/immich/releases/tag/v1.55.0) in the new version so I'll update the images and give it a test.

**Comment by nmfretz** [comment]
@JimSB there has been quite a few changes to how Immich is packaged for docker since the initial release on Umbrel. It now uses [typesense](https://hub.docker.com/r/typesense/typesense) for enhanced search functionality, and has some other changes that required updating the `docker-compose.yml`. I think I have made the correct changes based on this [example docker-compose.yml](https://github.com/immich-app/immich/blob/main/docker/docker-compose.yml). It is a little tricky because the example uses a single `.env` file passed to each container, but we need to pass in individual environment variables to the proper containers for our use case as an Umbrel app. I had to play around with adding certain env vars to certain containers to get things working properly again.

We can now give this a test and see if everything migrates properly and if all features are working.

**Comment by jrasm91** [comment]
FYI - the new release have facial recognition and partner sharing, so might as well bump it again :-)

**Comment by samip5** [comment]
FYI - current latest release is [1.56.1](https://github.com/immich-app/immich/releases/tag/v1.56.1) that's 17 hours old at this point.

**Comment by rpjcbs** [comment]
Current latest release is [1.57.1](https://github.com/immich-app/immich/releases/tag/v1.57.1)

**Comment by rpjcbs** [comment]
Might as well bump again, from v 1.59.0 both the server and app need to be running the same version to work correctly. These guys are pumping out these updates fast

**Comment by nmfretz** [comment]
@jrasm91 @samip5 @rpjcbs, very sorry for the delay while I have been focussed on other things. This update will be rolling out shortly.

**Comment by samip5** [comment]
> @jrasm91 @samip5 @rpjcbs, very sorry for the delay while I have been focussed on other things. This update will be rolling out shortly.

Latest is 1.60.0

**Comment by nmfretz** [comment]
Tested on amd64 and arm64. Going live 📸

Due to the large number of structural changes to Immich since this app was first submitted to Umbrel, I have overhauled this PR to:
- include new services introduced in recent versions of Immich
- replaced `exports.sh` with a custom yaml extension of env vars in the `docker-compose.yml`, such that the environment variable structure is as similar as possible to Immich's [example compose file](https://github.com/immich-app/immich/blob/main/docker/docker-compose.yml). This will make future updates easier.
- updated the app manifest to version 1.1 and included a pre-start script to ensure that new `model-cache` and `tsdata` directories are created and chown'd 1000:1000 for existing installs.

**Comment by nmfretz** [comment]
Note: this was merged as `Updating Immich to 1.54.1` https://github.com/getumbrel/umbrel-apps/commit/01d79dd223cee387b34ead64b7f7f92b0a0d365d. This should have referenced version 1.60.0

**Comment by rpjcbs** [comment]
Thanks a bunch @nmfretz

Really appreciated

**Comment by BubbyWoodz** [comment]
Please Update Immich to v1.132.0

**Pull request merged**
