### PR TITLE
Update Torq to v0.18.18

### PR DESCRIPTION
**Pull request by laitang2000**
Update Torq to v0.18.18 

  New features: 
  - Channel views can now be renamed via the title
  - Added filterable columns to Channel view
  - Tag sorting

  Bug fixes:

  - Fixed bug causing race conditions when saving a node
  - Activate Streams by default

Tested on real Rasberry PI

### CODE REVIEW

**Comment by ohenrik** [comment]
@nevets963 this update contains a fix for a bug that prevented new users from collecting data without manually configuring the node after install. 

We’re seeing a lot of new users and fear that they get a bad first impression. So we’re hoping to get this fix merged in quickly. 

I understand that you are probably busy, but thought I’d give a small nudge, sorry for disturbing you.

**Comment by nevets963** [comment]
@ohenrik Thanks for the ping, no worries. On it now

**Comment by ohenrik** [comment]
@nevets963 Thank you!

**Review by nevets963 — APPROVED** [review]
@laitang2000 Thanks for the app update PR!

Tested on `arm64` and `amd64`.

Merging now 🚀

**Pull request merged**
