### PR TITLE
2022 09 14 krystalbull update

### PR DESCRIPTION
**Pull request by Christewart**
Upgrade Krystal Bull to the 1.9.4 release of bitcoin-s

https://github.com/bitcoin-s/bitcoin-s/releases/tag/1.9.4

### CODE REVIEW

**Comment by nevets963** [comment]
@Christewart The updates keep coming! 😄  Are these ready for testing/review?

**Comment by Christewart** [comment]
> @Christewart The updates keep coming! smile Are these ready for testing/review?

They are! Sorry we found something wrong in the 1.9.3 release that we needed to do another release for. Hopefully this isn't giving you too much review burden. 

I'm running both 8ada88b and #149 on my personal umbrel

**Comment by nevets963** [comment]
@Christewart No worries, I'll make it my priority to test/review these now

**Comment by Christewart** [comment]
> @Christewart No worries, I'll make it my priority to test/review these now

What is your TG? we can do this bet too while you are at it 

https://github.com/getumbrel/umbrel-apps/pull/115#issuecomment-1244321300

**Pull request merged**
