### PR TITLE
Update nolooking to v0.2.0-alpha

### PR DESCRIPTION
**Pull request by DanGould**
Built for docker here: https://github.com/DanGould/nolooking/actions/runs/3509289629, but renamed so the hash doesn't match. From here on out we're building on tag @chaincase-app/nolooking

### CODE REVIEW

**Comment by nickfarrow** [comment]
Awesome, thanks for updating @DanGould

**Comment by DanGould** [comment]
Pushed a build with amd64 & arm64

**Comment by nickfarrow** [comment]
Tested!

**Comment by nickfarrow** [comment]
@nevets963 I see a different digest on 
https://hub.docker.com/layers/chaincase/nolooking/v0.2.1-alpha/images/sha256-905b6f8cb89a292e5f0d6cad3b5a093751725cb3d4981e046f9aac67fc201c1b

Both worked with `sudo ./scripts/app install nolooking` though 🤔

**Comment by nevets963** [comment]
@nickfarrow That is the image digest for `arm64` which if we use means that won't then work on `amd64`. If you do a `docker pull <image>`, it will return the multi-arch digest at the bottom.

**Review by nevets963 — COMMENTED** [review]
I just tested on `arm64` and `amd64` and this looks nearly good to go! Would you mind updating the release notes (`releaseNotes`) within `umbrel-app.yml` and then I'll get this merged in 🚀

**Comment by nickfarrow** [comment]
Added release notes. Thanks!

**Review by nevets963 — APPROVED** [review]
Everything looks great!

Merging now 🚀

**Pull request merged**
