### PR TITLE
LNDg v1.2.1

### PR DESCRIPTION
**Pull request by cryptosharks131**
Updates LNDg to v1.2.0
https://github.com/cryptosharks131/lndg/pkgs/container/lndg/28046226?tag=v1.2.0
https://github.com/cryptosharks131/lndg/releases/tag/1.2.0

### CODE REVIEW

**Review by nevets963 — APPROVED** [review]
Hey @cryptosharks131, thank you for the LNDg app update! Approved from me!

@cryptosharks131 Umbrel v0.5 introduced the 'App Proxy' which now protects all apps using the user's Umbrel password (and where appicable 2FA). This means we can drop secondary passwords for apps and improve the overall user experience. Reading the docs (https://github.com/cryptosharks131/lndg/blob/master/README.md#setup-lndg-initializepy-options) it looks like a password is mandatory atm. Would you consider making an app password optional, and then not using this with Umbrel?

Tested on AMD64 and ARM64 (Pi).

@lukechilds Do you also want to check this over?

**Comment by cryptosharks131** [comment]
The password is mandatory at the moment but I can look into the possibility of making it an optional system setting in a future update.

I have another build `v1.2.1` I will release in the next day or so to fix a small issue found with `v1.2.0`. It may be best to just wait for that build to be ready.

**Comment by cryptosharks131** [comment]
Updated images to v1.2.1 and requested for approval again.
https://github.com/cryptosharks131/lndg/pkgs/container/lndg/28159541?tag=v1.2.1
https://github.com/cryptosharks131/lndg/releases/tag/1.2.1

**Review by nevets963 — APPROVED** [review]
LNDg v1.2.1 tested on AMD64 and ARM64. Approved!

Will merge now.

**Pull request merged**
