### PR TITLE
Update maybe to 0.1.0-alpha.9

### PR DESCRIPTION
**Pull request by CaptainCodeman**
Left description as-is / didn't add release notes, as they still apply.

### CODE REVIEW

**Comment by sharknoon** [comment]
Thank you @CaptainCodeman for the update. Maybe we could add some Release Notes from https://github.com/maybe-finance/maybe/releases/tag/v0.1.0-alpha.8 . Please keep the release notes non-technical, for example:
```
What's New:

- Enhanced button design for a more unified look.
- Improved account settings and transaction updates.
- Fixed several bugs to make the app run smoother.
- Toast notifications can now be closed on demand.
```

**Comment by CaptainCodeman** [comment]
OK, will do - there's a fresh update so I'll include that

**Comment by sharknoon** [comment]
Wonderful, this PR looks good to me 😀

**Comment by nmfretz** [comment]
Thanks for the update @CaptainCodeman! And for the review @sharknoon 🙏

Tested and working well. Going live.

FYI @CaptainCodeman, rendering the yaml nicely in the app store is a little finicky. To get text to appear on a separate line you need to add blank newlines between them. See this commit for details: https://github.com/getumbrel/umbrel-apps/pull/1189/commits/597bcb9222d60663629542c7eacafbbcb914a996

Before:
image

After:
image

**Comment by CaptainCodeman** [comment]
> FYI @CaptainCodeman, rendering the yaml nicely in the app store is a little finicky. To get text to appear on a separate line you need to add blank newlines between them. See this commit for details: [597bcb9](https://github.com/getumbrel/umbrel-apps/commit/597bcb9222d60663629542c7eacafbbcb914a996)

Thanks for the extra feedback!

**Pull request merged**
