### PR TITLE
App Submission: Heimdall

### PR DESCRIPTION
**Pull request by AxelPilop**
Hello, I propose the addition of Heimdall to Umbrel

### CODE REVIEW

**Review by nevets963 — APPROVED** [review]
@AxelPilop Thanks so much for the PR to add Heimdall into the Umbrel App Store! The PR was overall good and I only patched up a couple of small things.

Tested on `arm64` and `amd64`.

We just need to create some graphics for the app which will subsequently live in this repo: https://github.com/getumbrel/umbrel-apps-gallery as soon as I have those made, we can merge this and get it launch into the app store! 🚀

**Comment by nevets963** [comment]
@AxelPilop We've prepared the graphics which is located in this PR: https://github.com/getumbrel/umbrel-apps-gallery/pull/36/files Do you think they're good too? If so, we'll merge everything and get this launched 😄

**Comment by AxelPilop** [comment]
@nevets963 It looks perfect to me, thanks to you

**Comment by nevets963** [comment]
@AxelPilop Our graphics designer did an awesome job 😄 Graphics are now merged, so this good to go. Merging now 🚀

**Pull request merged**
