### PR TITLE
App Submission: Remmina

### PR DESCRIPTION
**Pull request by IMPranshu**
# App Submission

### Remmina
...

### 256x256 SVG icon
https://github.com/IMPranshu/svg-logo/blob/main/Remmina.svg

...

### Gallery images
r5
r5
r4
r3
r2
r1

...

### I have tested my app on:
- [ ] [Umbrel dev environment](https://github.com/getumbrel/umbrel-dev)
- [x] [Umbrel OS on a Raspberry Pi 4](https://github.com/getumbrel/umbrel-os)
- [x] [Custom Umbrel install on Linux](https://github.com/getumbrel/umbrel#-installation)

### CODE REVIEW

**Review by nevets963 — APPROVED** [review]
@IMPranshu Many thanks for submitting Remmina! It's seriously impressive what can be done running these 'native' applications through Docker and into the browser.

Tested on `arm64` and `amd64`. Approved from me.

@mayankchhabra We need your help again here 😄 

Same again - once graphics are done, this can be merged in 🚀

**Comment by nevets963** [comment]
Gallery assets are located here: https://github.com/getumbrel/umbrel-apps-gallery/pull/26 Will start on final tests today before merging.

**Comment by nevets963** [comment]
Another great utility to add to the App Store. Merging now 🚀 🎄

**Comment by Niclassslua** [comment]
image

<br><br>

The remmina1 icon is very low quality.

I would suggest using the one I uploaded. It's 900x900.

<br><br>

remmina

**Comment by al-lac** [comment]
Hey @Niclassslua,

thanks for the suggestion!

The icons are already provided as svg files, so they should scale properly. Where did you take the screenshot and from which browser?

You can find the icons in the [umbrel-apps-gallery](https://github.com/getumbrel/umbrel-apps-gallery) repository, this is the file for remmina: https://github.com/getumbrel/umbrel-apps-gallery/blob/master/remmina/icon.svg

This is how it looks for me where the scaling works fine:
CleanShot 2025-09-15 at 11 31 14@2x

**Pull request merged**
