### PR TITLE
App Submission: Rotki (Open-Source Crypto Portfolio Tracker)

### PR DESCRIPTION
**Pull request by Xosten**
# App Submission

### App name
Rotki

### 256x256 SVG icon
https://svgshare.com/i/nrs.svg

### Gallery images
image
image
image
image
image

### I have tested my app on:
- [ ] [Umbrel dev environment](https://github.com/getumbrel/umbrel-dev)
- [ ] [Umbrel OS on a Raspberry Pi 4](https://github.com/getumbrel/umbrel-os)
- [x] [Custom Umbrel install on Linux](https://github.com/getumbrel/umbrel#-installation)

### CODE REVIEW

**Review by nevets963 — APPROVED** [review]
@Xosten Many many thanks for submitting rotki into the Umbrel App Store! It'll definitely be useful for a lot of Umbrel users!

The PR was overall good. I've made a few tweaks to the PR, including removing the `exports.sh` which isn't needed anymore and simplifies apps. I found that the the env. vars. you had didn't do anything for me, so they were removed. I found that the container was still running as `root`.

Tested on `arm64` and `amd64`. This is approved from me 🚀 

@mayankchhabra Could you help prepare the app store graphics please?

**Comment by Xosten** [comment]
> @Xosten Many many thanks for submitting rotki into the Umbrel App Store! It'll definitely be useful for a lot of Umbrel users!
> 
> The PR was overall good. I've made a few tweaks to the PR, including removing the `exports.sh` which isn't needed anymore and simplifies apps. I found that the the env. vars. you had didn't do anything for me, so they were removed. I found that the container was still running as `root`.
> 
> Tested on `arm64` and `amd64`. This is approved from me 🚀
> 
> @mayankchhabra Could you help prepare the app store graphics please?

Thanks man! This one was definitely a brainteaser for me, apologies for the few things I missed out! Can't wait to see the application live in the store!

**Comment by Xosten** [comment]
Hi @nevets963,
FYI, I have opened a PR for the images https://github.com/getumbrel/umbrel-apps-gallery/pull/17

**Comment by nevets963** [comment]
@Xosten They look pretty good! @mayankchhabra Usually creates these to ensure the design is consistent etc. I'll let him chime in here with what he thinks

**Comment by Xosten** [comment]
> @Xosten They look pretty good! @mayankchhabra Usually creates these to ensure the design is consistent etc. I'll let him chime in here with what he thinks

Sure no problem! Just wanted to help @mayankchhabra 😉. Let's wait for his feedback 😄

**Comment by nevets963** [comment]
Gallery assets have been submitted here: https://github.com/getumbrel/umbrel-apps-gallery/pull/19

I will do 1 final test and then if good, merge 🚀

**Comment by Xosten** [comment]
> Gallery assets have been submitted here: [getumbrel/umbrel-apps-gallery#19](https://github.com/getumbrel/umbrel-apps-gallery/pull/19)
> 
> I will do 1 final test and then if good, merge 🚀

Awesome!!! Can't wait to see the application live in the App Store!

**Comment by LefterisJP** [comment]
Hey thank you so much for adding rotki to Umbrel :bow:

**Pull request merged**
