### PR TITLE
Update Torq to v0.19.1

### PR DESCRIPTION
**Pull request by maxwedwards**
Big upgrade to Torq!

Tested on a real Raspberry Pi.

Our pictures are now a bit old and not representative of the new features. May we please update them? New screenshots:

### CODE REVIEW

**Comment by nmfretz** [comment]
Fantastic. Thanks @maxwedwards. Testing now. 

> Our pictures are now a bit old and not representative of the new features. May we please update them? New screenshots:

Absolutely. What text would you like to appear above each of the gallery images? See here for the current gallery: https://apps.umbrel.com/app/torq

**Review by nmfretz — COMMENTED** [review]
Tested on amd64 and arm64 for new and existing installs and everything is working great!

One small change to make (see below) if you want 5 gallery images.

**Comment by ohenrik** [comment]
@nmfretz Here is the text I think works with the images. I numbered them and and the name following the number is the title of the page in the screenshot.

1. Dashboard:
An advanced Lightning node management

2. Rebalancer
Automate your node with powerful custom workflows.

3. Inspect Channel page
Fetch and analyse data from any point in time.

4. All channels Page
Instantly see channel details, add tags and organize the data exactly as you prefer.

5. Forwards Summary
See all your routing activity at a glance.

**Comment by maxwedwards** [comment]
Hopefully that's everything you need @nmfretz.

**Comment by ohenrik** [comment]
Great!

Both suggestions looks better to me. So choose either one is fine with me. Perhaps leaning towards the first you proposed.

**Comment by nmfretz** [comment]
Gallery update is done. Going live now! Thanks again @maxwedwards and @ohenrik.

**Pull request merged**
