### PR TITLE
App Submission: SpeedTest

### PR DESCRIPTION
**Pull request by IMPranshu**
# App Submission

### SpeedTest Tracker
...

### 256x256 SVG icon
https://github.com/IMPranshu/svg-logo/blob/main/test.svg

...

### Gallery images
Screenshot from 2022-11-14 02-11-07
Screenshot from 2022-11-14 02-10-50
Screenshot from 2022-11-14 02-10-42

...

### I have tested my app on:
- [ ] [Umbrel dev environment](https://github.com/getumbrel/umbrel-dev)
- [x] [Umbrel OS on a Raspberry Pi 4](https://github.com/getumbrel/umbrel-os)
- [x] [Custom Umbrel install on Linux](https://github.com/getumbrel/umbrel#-installation)

### CODE REVIEW

**Comment by PoorPocketsMcNewHold** [comment]
Tested it, and it works pretty nicely.
The icon would need to be changed, however, but that's really all I can complain.

**Comment by nevets963** [comment]
I think this would be a great addition to the App Store, but unfortunately they don't have versioned Docker images. They have `latest` and `dev` tag e.g. https://github.com/getumbrel/umbrel-apps/pull/279/files#diff-b2d73370228225dc710f82c1349ac7ca2fd2ebedfba51529c151bbb8c3d11844R10 which could change at any point making the digest then invalid.

**Comment by matbrgz** [comment]
How to fix that? I can help.

**Comment by nevets963** [comment]
@matbrgz Ideally, we would need a Docker image pushed a registry with the tag `v1.12.0` (or similar) as that appears to be the latest release (https://github.com/henrywhitaker3/Speedtest-Tracker/releases/tag/v1.12.0).

**Comment by nevets963** [comment]
Closing due to challenges with Docker images (details here: https://github.com/getumbrel/umbrel-apps/pull/279#issuecomment-1342857743). Happy to re-open if this can be resolved.

**Pull request closed without merging**
