### PR TITLE
Update Immich to v1.77

### PR DESCRIPTION
**Pull request by ankit5902**
Updated image to v1.76.1 for

- `immich-server` (the same `immich-server` tag is used under `server` and `microservices)`
- `immich-machine-learning`
- `immich-web`
- `immich-proxy`

Did not change `typesense:0.24.1`, `redis:6.2-alpine` or `postgres:14-alpine`

### CODE REVIEW

**Comment by ankit5902** [comment]
Today, a new version was released and as a result, I have updated the image to v1.77.0.

**Comment by nmfretz** [comment]
Thank you for keeping this up to date @ankit5902. Excellent work! I made a slight tweak to the release notes to remove mention of "new features" for this release, and remove the highlighted improvement for the mobile app.

Tested on arm64 and x86(amd64). Going live 📸.

**Comment by u1f5a4** [comment]
Please update 🙏

**Comment by ankit5902** [comment]
Hey @u1f5a4, I have created PR #781 to update Immich. You'll receive an update once the PR is merged.

**Comment by Metatronovich** [comment]
Please update to [v1.105.1](https://github.com/immich-app/immich/releases/tag/v1.105.1)
its currently on 103 and unusable with ios app

**Pull request merged**
