### PR TITLE
App Submission: Homebox

### PR DESCRIPTION
**Pull request by IMPranshu**
# App Submission

### Homebox
...

### 256x256 SVG icon
https://github.com/IMPranshu/svg-logo/blob/main/homebox.svg
...

### Gallery images
Screenshot 2023-07-19 at 1 15 02 PM
Screenshot 2023-07-19 at 1 14 51 PM
Screenshot 2023-07-19 at 1 14 39 PM
Screenshot 2023-07-19 at 1 14 29 PM

...

### I have tested my app on:
- [x] [Umbrel dev environment](https://github.com/getumbrel/umbrel-dev)
- [x] [Umbrel OS on a Raspberry Pi 4](https://github.com/getumbrel/umbrel-os)
- [x] [Custom Umbrel install on Linux](https://github.com/getumbrel/umbrel#-installation)

### CODE REVIEW

**Comment by Xosten** [comment]
Duplicate of #501, this PR should be closed

**Comment by IMPranshu** [comment]
> Duplicate of #501, this PR should be closed

Sorry @. I didn't see that you already had a PR with this app. 

But my PR seems to solve the `Root` issue for this because I created a Dockerfile which doesn't require root permission as it shouldn't in the first place and used it to run the app.
Did you see my commits?

**Comment by Xosten** [comment]
> > Duplicate of #501, this PR should be closed
> 
> Sorry @. I didn't see that you already had a PR with this app.
> 
> But my PR seems to solve the `Root` issue for this because I created a Dockerfile which doesn't require root permission as it shouldn't in the first place and used it to run the app. Did you see my commits? Do check the docker hub for the image I have pushed to `impranshu/homebox`

I think Umbrel's best practice is to pull from the original author's repository. Your's is a fork of the original one. The rootless version for homebox has been made, we're just waiting to make the image available in their repo.

**Comment by nmfretz** [comment]
Closing in favour of https://github.com/getumbrel/umbrel-apps/pull/501, which was already open and under review.

**Comment by Xosten** [comment]
Hey @IMPranshu, just wanted to let you know that Homebox has been added to the store and so available for download if you're interested ;)

**Pull request closed without merging**
