### PR TITLE
Bump lndboss to v2.19.1

### PR DESCRIPTION
**Pull request by niteshbalusu11**
Signed-off-by: Nitesh Balusu <84944042+niteshbalusu11@users.noreply.github.com>

Bumping LndBoss to v.2.19.1

### CODE REVIEW

**Comment by niteshbalusu11** [comment]
Any update on this please? It has some important bug fixes.

@nevets963 @lukechilds

**Comment by nevets963** [comment]
@niteshbalusu11 I'm no longer at Umbrel. @nmfretz Can help you here.

**Comment by nmfretz** [comment]
Sorry for the delay @niteshbalusu11, I had my head down to focus on other umbrel items.

Tested and going live ⚡️

**Comment by niteshbalusu11** [comment]
Thank you!

**Pull request merged**
