### PR TITLE
Update Torq to v0.18.19

### PR DESCRIPTION
**Pull request by laitang2000**
Bug fix - enable data streams by default

Tested on real Rasberry PI

### CODE REVIEW

**Comment by ohenrik** [comment]
@nevets963 Sorry to bother you again, the previous update did not fix the bug for new Umbrel users as we thought it would (just for installations done with the install script). We missed it since we did not simulate fresh installations.

Could you perhaps fast track this update as well so that we get the update in before the weekend? We're still seeing a sharp increase in new users.

Again sorry for all the mess.

**Comment by nevets963** [comment]
@ohenrik On it now

**Review by nevets963 — APPROVED** [review]
Tested on `arm64` and `amd64`.

Merging now 🚀

**Comment by ohenrik** [comment]
Thank you again @nevets963! Much appreciated ❤️

**Comment by nevets963** [comment]
@ohenrik No worries, have a great weekend!

**Pull request merged**
