### PR TITLE
RTL Update on CLN

### PR DESCRIPTION
**Pull request by ShahanaFarooqui**
RTL Update on CLN

### CODE REVIEW

**Review by nevets963 — COMMENTED** [review]
@ShahanaFarooqui Just before I review this, we can perhaps also update the release notes here. I looked at the changelog for 0.13.0 and I see specific updates for Core Lightning. So perhaps here, we can use this text for the release notes? However, open to suggestions :)

```
- Liquidity Ads interface for viewing ads, researching nodes and buying channels
- Liquidity Ads configuration to publish ads on the network
- Regtest support
- Dashboard performance improvements
```

**Comment by ShahanaFarooqui** [comment]
Hi, thank you for release notes suggestions. I think they covered all major features. We can move forward with these.

**Review by nevets963 — COMMENTED** [review]
@ShahanaFarooqui I just noticed the update for Core Lightning itself. Is v0.9.0 of `c-lightning-rest` a hard requirement to work with RTL v0.13?

**Comment by ShahanaFarooqui** [comment]
0.9.0 has liquidity ads APIs. So RTL’s liquidity ads feature will not work without this update but it will not break anything else.

**Pull request merged**
