### PR TITLE
Update lnd to 0.15.2-beta

### PR DESCRIPTION
**Pull request by MaxKotlan**
Fixes bug that causes lnd to crash on startup.

### CODE REVIEW

**Comment by MaxKotlan** [comment]
Tested on arm and x64. Both nodes working as expected after update.

**Comment by lukechilds** [comment]
Thanks for the quick submission and testing on this guys, really appreciate it! Just doing some quick testing on my end and we'll make this live.

**Comment by lukechilds** [comment]
Thanks very much @MaxKotlan, tested on amd64/arm64 mainnet/testnet and merged!

@aphex3k @mccolister1017 appreciate your adjacent PRs too, I gave you all commit credits on the final merged commit.

**Comment by MaxKotlan** [comment]
No problem @lukechilds. Happy to help.

**Pull request merged**
