### PR TITLE
Up N8N version to 0.233.1

### PR DESCRIPTION
**Pull request by benborges**

### CODE REVIEW

**Comment by nmfretz** [comment]
Thanks @benborges. Based on the n8n releases here it looks like the latest stable release is [0.233.1](https://github.com/n8n-io/n8n/releases/tag/n8n%400.233.1): https://github.com/n8n-io/n8n/releases

There's a ton of different tags available on docker hub, but the latest stable one is what we should use.

If you run `docker pull n8nio/n8n:0.233.1` the output will show you the correct sha256 digest to use for the multi-arch image.

**Comment by benborges** [comment]
Oh alright, I was indeed confused by the tag to use, it's now 0.233.1

**Comment by Xosten** [comment]
Closes #635 when merged

**Comment by nmfretz** [comment]
Thanks @benborges! I see that n8n just came out with another update (0.234.1), so I bumped the image and updated the release notes.

Going live.

**Pull request merged**
