### PR TITLE
Update PeerSwap Web UI to v1.5.7

### PR DESCRIPTION
**Pull request by Impa10r**
Adds channel Auto Fee functionality plus various enhancements.

image

### CODE REVIEW

**Comment by nmfretz** [comment]
Thanks for the update @Impa10r. I'm just re-syncing Elements Core to test.

**Comment by nmfretz** [comment]
Hey @Impa10r, I changed the environment variable `NO_HTTPS` from:
```yaml
NO_HTTPS: true
```

to

```yaml
NO_HTTPS: "true"
``` 

Can you please test to see that peerswap is consuming this correctly?

The reason I did this is that I noticed Docker Compose v1 and v2 treat `boolean` values differently:

V1 does not allow booleans for environment keys: https://docs.docker.com/compose/release-notes/#170

So users running umbrelOS 0.5.4 (which uses Compose v1.29.2) will get a broken install/update, with this error:
`services.web.environment.NO_HTTPS contains true, which is an invalid type, it should be a string, number, or a null`

V2, however, does allow certain booleans:
- string interpolation in 2.0: https://docs.docker.com/compose/release-notes/#compose-file-version-2x
- boolean values of `true` and `false` allowed as of version 2.17.0: https://docs.docker.com/compose/release-notes/#2170

umbrelOS 1.x uses Compose v2.27.1, so the original boolean value you used works fine.

Please let me know if this change works for you and then I'll merge.

**Review by Impa10r — COMMENTED** [review]
Thanks! It is consumed correctly.

**Comment by nmfretz** [comment]
Perfect, thanks for checking! Going live.

**Pull request merged**
