### PR TITLE
Update RoboSats to v0.7.0-alpha

### PR DESCRIPTION
**Pull request by KoalaSat**
Update RoboSats to latest v0.7.0-alpha

Untested. Exactly replicated the steps to update to v0.6.0-alpha https://github.com/getumbrel/umbrel-apps/pull/1022

### CODE REVIEW

**Comment by KoalaSat** [comment]
Looks like there is a problem with the image generation, I'll take a look into it and get back

**Comment by nmfretz** [comment]
Thanks @KoalaSat! Let me know as soon as you're ready for me to take a look.

**Comment by KoalaSat** [comment]
@nmfretz Fixed the problem, I found that the landing page was never showing up and it just got stuck in infinite loading. Now it seems to work

**Comment by nmfretz** [comment]
Perfect, thanks a ton for keeping Robosats up to date @KoalaSat. 

I have reviewed and tested on both arm64 and x86 for fresh installs and app updates. 

Going live 🤖

**Pull request merged**
