### PR TITLE
Nextcloud: Migrate from v22 to v25

### PR DESCRIPTION
**Pull request by nevets963**
This PR adds a hook to cycle through the intermediate versions of Nextcloud from v22 and v25 and installs them in order for us to reliability upgrade users to the latest version (v25).

Tested:
- Upgrade process from v22.1 to v25
- Upgrade process from v22.2 to v25
- Fresh install of v25
... on my `arm64` and `amd64` Umbrels

### CODE REVIEW

**Comment by nevets963** [comment]
@Xosten I just want to say, I do appreciate the original PR (https://github.com/getumbrel/umbrel-apps/pull/257) to update Nextcloud. As I said, it's a tricky update process and you can see from this PR that it was pretty involved to reliably update  to v25.

**Comment by pynixis** [comment]
Great update! Love all the new changes.

**Comment by Xosten** [comment]
> @Xosten I just want to say, I do appreciate the original PR (#257) to update Nextcloud. As I said, it's a tricky update process and you can see from this PR that it was pretty involved to reliably update to v25.

I totally got it after looking at your PR. Big GG to you @nevets963 👏🏻 !

**Comment by enjikaka** [comment]
Skärmavbild 2023-02-11 kl  00 25 07

Locked out of nextcloud after the update. Trusted domains still looks OK and I don't see anything in the logs. Ideas?

**Comment by enjikaka** [comment]
Finally managed to get access again. Needed to edit version.php, config.php and docker-compose back to 22.2.10.2. The pre-start script does not work since the version every one has is `22.2.10.2-patch` which does not strict equal `22.2.10.2` in the script. My IPs also got scrambled so I had to manually change the database and redis host url in config.php from 10.x IPs to `nextcloud_db_1` and `nextcloud_redis_1`.

**Pull request merged**
