### PR TITLE
RTL v0.13.1

### PR DESCRIPTION
**Pull request by ShahanaFarooqui**
RTL v0.13.1

### CODE REVIEW

**Review by nevets963 — COMMENTED** [review]
Hey @ShahanaFarooqui Thanks a huge amount for the PR to update RTL! Would you mind re-submitting with 2 PRs for each app? Just incase there is a regression with one, we can easily revert the commit, rather than reverting both?

**Comment by ShahanaFarooqui** [comment]
Hi, Updated this to keep RTL on LND update only and created PR #176 for RTL on CLN update. Thank you.

**Review by nevets963 — APPROVED** [review]
@ShahanaFarooqui Thanks for submitting an update for RTL! I've tested this on `arm64` and `amd64`.

I've added some release notes for the update. They will appear in the Umbrel UI and help users understand the changes within the update. Can you check them over and make any neccessary modifications?

This is approved from me! I'll merge once you're happy with the release notes.

**Comment by ShahanaFarooqui** [comment]
I am unable to find release notes for this one. Could you please explain how to check release notes for LND's RTL? 

In the meantime, I collected some release notes below. Please share your notes or feel free to use mine:

- Events/day view for routing history report
- Filtering non routing peers on routing page
- Invoice lookup feature
- Circular rebalance infographics
- Other bug fixes

**Comment by nevets963** [comment]
I've used your release notes here, and this how they get displayed in the Umbrel UI:
Screenshot 2022-10-01 at 14 51 03

**Pull request merged**
