### PR TITLE
Update rotki to v.1.32.2

### PR DESCRIPTION
**Pull request by Xosten**
Updating Rotki as it's a few versions behind and there's also a bug which is fixed in the latest version (reported via [rotki discord](https://discord.com/channels/657906918408585217/745172610240872508/1228798019030487140)).

### CODE REVIEW

**Comment by LefterisJP** [comment]
Also guys from umbrel is there any way for us to automatically update it as we make a release?

**Comment by Xosten** [comment]
Sorry I forgot to update the manifest @nmfretz. Been a while since last update, I’m becoming rusty on the steps 🫣

**Comment by nmfretz** [comment]
Awesome, thanks for the update @Xosten! Great to see you back here again 🤝.

I have bumped the version in the umbrel-app.yml so that users are notified that an update is available and have also added release notes.

**Comment by nmfretz** [comment]
> Sorry I forgot to update the manifest @nmfretz. Been a while since last update, I’m becoming rusty on the steps 🫣

No worries at all, I figured it had been a while 🤭

**Comment by nmfretz** [comment]
@LefterisJP at this point there isn't a way to issue updates automatically on the official app store. It has to go through our review process. You can get around this by creating a Community App Store that you have full control over. Then users can install the app from that community app store. 

We are about to revamp the app framework on umbrelOS so stay tuned.

**Pull request merged**
